- alias: "toilet: lights"
  id: d4e1013c-70e8-432c-a3fc-7923bd3f0639
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded

    - platform: state
      entity_id:
        - binary_sensor.motion_toilet_presence
      from: "off"
      to: "on"

    - platform: state
      entity_id:
        - binary_sensor.motion_toilet_presence
      from: "on"
      to: "off"
      for:
        seconds: 30

  action:
    - choose:
        - alias: "when triggered"
          conditions:
            - alias: "and motion is detected"
              condition: state
              entity_id:
                - binary_sensor.motion_toilet_presence
              state: "on"

            - alias: "and we are home (cat's can poop in the dark)"
              condition: state
              entity_id:
                - input_boolean.house_mode_away
              state: "off"

          sequence:
            - choose:
              - conditions:
                - alias: "if it's night"
                  condition: time
                  after: input_datetime.time_goodnight
                  before: input_datetime.time_goodmorning

                sequence:
                - alias: "turn on the lights at low level"
                  service: light.turn_on
                  target:
                    entity_id: light.upper_toilet
                  data:
                    brightness: 70

              default:
              - alias: "turn on the lights"
                service: light.turn_on
                target:
                  entity_id: light.upper_toilet
                data:
                  brightness: 255

      default:
        - alias: "turn off the lights"
          service: light.turn_off
          target:
            entity_id: light.upper_toilet
