- alias: "Update 20a fuse template when states haven't changed"
  id: 8f555a3e-2ede-491e-9042-3179ffd2407c
  trace:
    stored_traces: 10
  trigger:
    - platform: state
      entity_id: sensor.export_power_below_20a
      for: "00:00:30"
  condition:
    - condition: numeric_state
      entity_id:
        - sensor.export_power_below_20a
      above: 13999
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.export_power_below_20a
