- alias: "Nordpool: reload when hung"
  id: a7d69bb8-8f5b-46d2-860e-3bcfb9c2cc2d
  trace:
    stored_traces: 10

  trigger:
    - platform: time_pattern
      hours: "*"

    # - platform: event
    #   event_type:
    #     - automation_reloaded

  variables: 
    np_update: >
      {% set np_list = ['sensor.nordpool_se1', 'sensor.nordpool_se2', 'sensor.nordpool_se3', 'sensor.nordpool_se4'] %}
      {% set np_data = namespace(entities=[]) %}
      {% for s in np_list %}
        {% if (as_timestamp(now()) - as_timestamp(states[s].last_updated) > 7200) %}
          {% set np_data.entities = np_data.entities + [s] %}
        {% endif %}
      {% endfor %}
      {{ np_data.entities }}

  condition: []

  action:
    - choose:
      - conditions: "{{ np_update != '' }}"

        sequence:
          # - service: system_log.write
          #   data:
          #     message: "boop: {{ np_update }}"

          - service: homeassistant.reload_config_entry
            target:
              entity_id: "{{ np_update }}"
