- alias: Template reloaded
  description: "fires a event on templete reload event that templates can trigger on"
  trace:
    stored_traces: 10
  id: 7d34c05e-0976-4a49-b8fd-9cfd77c4f526
  triggers:
    - trigger: event
      event_type: event_template_reloaded
  conditions: []
  actions:
    - event: my_event_template_reloaded
      event_data: {}
  mode: single
