# credits for this code goes to rindlerblabla

- alias: "Z2M: device leave notification"
  id: 71e990e2-1f77-4985-9b7b-76dc9750d17a
  trace:
    stored_traces: 10
  
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/bridge/event
      payload: device_leave
      value_template: "{{ value_json.type}}"

  condition: []

  action:
    - wait_for_trigger:
        - platform: mqtt
          topic: zigbee2mqtt/bridge/event
          payload: device_joined
          value_template: "{{ value_json.type}}"
      timeout:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    - if:
        - condition: template
          value_template: "{{ wait.trigger is none }}"
      then:
        - service: notify.castle
          data:
            title: Zigbee2MQTT
            message: "{{ now().strftime('%H:%M:%S') }} - Z2M tappade kontakten med {{ trigger.payload_json.data.friendly_name }}."