- alias: "bathroom downstairs: lights"
  id: 2f16522d-300d-4c7f-8a5c-d00d283b9438
  mode: queued
  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded

    - trigger: state
      entity_id:
        - binary_sensor.motion_bathroom_downstairs_occupancy
      from: "off"
      to: "on"

    - trigger: state
      entity_id:
        - binary_sensor.motion_bathroom_downstairs_occupancy
      from: "on"
      to: "off"
      for:
        seconds: 120

  actions:
    - choose:
        - alias: "when triggered"
          conditions:
            - alias: "and motion is detected"
              condition: state
              entity_id:
                - binary_sensor.motion_bathroom_downstairs_occupancy
              state: "on"

            - alias: "and we are home (cat's can poop in the dark)"
              condition: state
              entity_id:
                - input_boolean.house_mode_away
              state: "off"

          sequence:
            - alias: "turn on the lights"
              action: light.turn_on
              target:
                entity_id: light.bathroom_downstairs_mirror
              data:
                brightness: 255

      default:
        - action: light.turn_off
          target:
            entity_id: light.bathroom_downstairs_mirror
