- alias: "bathroom downstairs: lights"
  id: 2f16522d-300d-4c7f-8a5c-d00d283b9438
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded

    - platform: state
      entity_id:
        - binary_sensor.bathroom_downstairs_presence
      from: "off"
      to: "on"

    - platform: state
      entity_id:
        - binary_sensor.bathroom_downstairs_presence
      from: "on"
      to: "off"
      for:
        minutes: 1

  action:
    - choose:
        - alias: "when triggered"
          conditions:
            - alias: "and motion is detected"
              condition: state
              entity_id:
                - binary_sensor.bathroom_downstairs_presence
              state: "on"

            - alias: "and we are home (cat's can poop in the dark)"
              condition: state
              entity_id:
                - input_boolean.house_mode_away
              state: "off"

          sequence:
            - alias: "turn on the lights"
              service: light.turn_on
              target:
                entity_id: light.bathroom_downstairs_mirror

      default:
        - service: light.turn_off
          target:
            entity_id: light.bathroom_downstairs_mirror
