platform: template
name: Current time
id: show_current_time
update_interval: never
device_class: timestamp
lambda: |-
  auto time = id(time_sntp).now();
  // char buf[30];
  // sprintf(buf, "%d", time);
  // std::string s = buf;
  ESP_LOGD("main", "time: %d", time);
  return {};
