- platform: generic_thermostat
  unique_id: "02f818e8-9d5d-4651-8956-4a46e56ba6c4"
  name: "Earth cellar"
  heater: switch.earth_cellar_radiator
  target_sensor: sensor.earth_cellar_climate_temperature
  min_temp: 0
  max_temp: 4
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  precision: 0.1

- platform: generic_thermostat
  unique_id: 8384b298-8282-4343-a8af-31afad1570ad
  name: "Techroom ventilation"
  heater: switch.techroom_ventilation_plug
  ac_mode: true
  target_sensor: sensor.techroom_temperature
  min_temp: 7
  max_temp: 30
  target_temp_step: 1