- platform: group
  name: family
  services:
    - service: mobile_app_kb2003
    - service: mobile_app_isabells_iphone

- platform: telegram
  name: castle
  chat_id: !secret telegram_id_castle

- platform: telegram
  name: castle_log
  chat_id: !secret telegram_id_castle_log