homeassistant:
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# integrations
http: !include integrations/http.yaml
influxdb: !include integrations/influxdb.yaml
notify: !include integrations/notify.yaml
recorder: !include integrations/recorder.yaml
spotify: !include integrations/spotify.yaml
tts: !include integrations/tts.yaml

automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include_dir_merge_list cameras/
group: !include_dir_merge_list groups/
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_list scripts/
sensor: !include_dir_merge_list sensors/
