homeassistant:
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# http access settings
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy_1

# Text to speech
tts:
  - platform: google_translate

recorder: !include recorder.yaml
influxdb: !include influxdb.yaml
notify: !include notify.yaml

# spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors/
sensor: !include_dir_merge_list sensors/
camera: !include_dir_merge_list cameras/
script: !include_dir_merge_list scripts/
scene: !include_dir_merge_list scenes/
