homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

default_config:

# integrations
browser_mod: !include integrations/browser_mod.yaml
climate: !include integrations/climate.yaml
ffmpeg: !include integrations/ffmpeg.yaml
frontend: !include integrations/frontend.yaml
http: !include integrations/http.yaml
influxdb: !include integrations/influxdb.yaml
google_assistant: !include integrations/google_assistant.yaml
logger: !include integrations/logger.yaml
#modbus: !include integrations/modbus.yaml
notify: !include integrations/notify.yaml
powercalc: !include integrations/powercalc.yaml
recorder: !include integrations/recorder.yaml
tts: !include integrations/tts.yaml
utility_meter: !include integrations/utility_meter.yaml
# deprecated
#google: !include integrations/google.yaml
#spotify: !include integrations/spotify.yaml

automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include_dir_merge_list cameras/
modbus: !include_dir_merge_list modbus/
mqtt:
  sensor: !include_dir_merge_list mqtt/sensors/
  binary_sensor: !include_dir_merge_list mqtt/binary_sensors/
scene: !include_dir_merge_list scenes/
sensor: !include_dir_merge_list sensors/
template: !include_dir_merge_list templates/

group: !include_dir_merge_named groups/
input_boolean: !include_dir_merge_named input/boolean/
input_datetime: !include_dir_merge_named input/datetime/
input_number: !include_dir_merge_named input/number/
input_select: !include_dir_merge_named input/select/
input_text: !include_dir_merge_named input/text/
script: !include_dir_merge_named scripts/
