platform: template
name: Get current time
entity_category: diagnostic
on_press:
  then:
    - component.update: show_current_time
    - lambda: |-
        if (id(time_sntp).now().is_valid()) {
          id(show_current_time).publish_state(id(time_sntp).now().timestamp);
        }
