- alias: "Kitchen: Coffee water level meter"
  id: 20fa1fcc-eae1-4428-9e2b-cfea2619e154
  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded

    - trigger: state
      entity_id: sensor.coffee_maker_state

  condition: []

  action:
    - choose:
        conditions:
          - condition: state
            entity_id: sensor.coffee_maker_state
            state: "off"

        sequence:
          - action: light.turn_off
            target:
              entity_id: light.coffeemaker_water_level_light

      default:
        - action: light.turn_on
          target:
            entity_id: light.coffeemaker_water_level_light
        - choose:
            - conditions:
                - condition: state
                  entity_id: light.kitchen_bench
                  state: "off"
                - condition: state
                  entity_id: input_boolean.house_mode_bright_hallway
                  state: "off"
              sequence:
                action: light.turn_on
                target:
                  entity_id: light.kitchen_bench
