- alias: "Kitchen: lights"
  id: 12efc75c-0603-4bd2-91d9-3cffa6159a82
  triggers:
    # - trigger: state
    #   entity_id:
    #     - input_boolean.house_mode_bright_inside

    - trigger: state
      id: movement
      entity_id:
        - input_boolean.kitchen_movement

    # - trigger: time
    #   at:
    #     - input_datetime.time_goodmorning
    #     - input_datetime.time_goodnight

    - trigger: state
      id: nightaway
      entity_id:
        - input_boolean.house_mode_away
        - input_boolean.house_mode_sleep
      from: "off"
      to: "on"

    # - trigger: state
    #   id: remote
    #   entity_id:
    #     - sensor.kitchen_remote_action
    #     - sensor.kitchen_remote_2_action
    - trigger: state
      entity_id:
        - event.kitchen_remote_action
        - event.kitchen_remote_2_action
      not_from: unavailable
      id: remote

    - trigger: state
      id: senile
      entity_id:
        - input_boolean.kitchen_movement
      from: "on"
      to: "off"
      for:
        minutes: "{{ states('input_number.kitchen_timeout')|int }}"

  actions:
    choose:
      - conditions:
          - condition: trigger
            id: movement
        sequence:
          - choose:
              - conditions: '{{ states("input_boolean.kitchen_movement") == "on" }}'
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: light.kitchen_sink
                    data:
                      brightness: 255
                      #transition: 1
            default:
              - action: light.turn_off
                target:
                  entity_id: light.kitchen_sink
                data:
                  transition: 5

      - conditions:
          # when no movement is detected for a fair amount of time, consider kitchen empty and that 'someone' forgot to turn off the lights
          - condition: trigger
            id: senile
        sequence:
          # turn off all lights
          - action: light.turn_off
            entity_id:
              - light.kitchen_island
              - light.kitchen_table

      - conditions:
          - condition: trigger
            id: remote

        sequence:
          - variables:
              #action: "{{ trigger.to_state.state }}"
              action: "{{ trigger.to_state.attributes.event_type }}"

          # - service: system_log.write
          #   data:
          #     message: "trigger: {{ trigger }}"

          - choose:
              - alias: "big pressed"
                conditions: "{{ action in ['big-press', 'on', 'brightness_up_click'] }}"
                sequence:
                  - choose:
                      - conditions: "{{ states('light.kitchen_table') == 'off' }}"
                        sequence:
                          - action: light.turn_on
                            target:
                              entity_id:
                                - light.kitchen_table
                            data:
                              brightness: 255
                    default:
                      - action: light.turn_off
                        target:
                          entity_id:
                            - light.kitchen_table

              - alias: "small pressed"
                conditions: "{{ action in ['small-press', 'off', 'brightness_down_click'] }}"
                sequence:
                  - action: light.toggle
                    target:
                      entity_id: light.kitchen_island
              - alias: "left pressed"
                conditions: "{{ action in ['left-press', 'arrow_left_click'] }}"
                sequence:
                  - action: light.toggle
                    target:
                      entity_id: light.kitchen_bench
              - alias: "right pressed"
                conditions: "{{ action in ['right-press', 'arrow_right_click'] }}"
                sequence:
                  - action: light.toggle
                    target:
                      entity_id: light.conservatory_ceiling

      - conditions:
          - condition: trigger
            # when night/away mode is active
            id: nightaway
        sequence:
          - action: light.turn_off
            # turn of regular lights
            target:
              entity_id:
                - light.kitchen_sink
                - light.kitchen_table
                - light.kitchen_island

      # - conditions:
      #     - condition: state
      #       # when there is daylight
      #       entity_id:
      #         - input_boolean.house_mode_bright_inside
      #       state: "on"

      #   sequence:
      #     - &turn_off # turn off lights
      #       action: light.turn_off
      #       target:
      #         entity_id:
      #           - light.kitchen_lamp
      #           - light.kitchen_window_1
      #           - light.rice_lamp
      #           - light.kitchen_bench
      #       data:
      #         transition: 5

      # - conditions:
      #     - condition: or
      #       conditions:
      #         - condition: and
      #           # turn on lights if
      #           conditions:
      #             - condition: time
      #               # at specific time in the morning
      #               after: input_datetime.time_goodmorning
      #               # but before a specific time in the evening
      #               before: input_datetime.time_goodnight

      #   sequence:
      #     - &scene_turn_on
      #       action: scene.turn_on
      #       target:
      #         entity_id:
      #           - scene.kitchen_ambience_lights_cozy
      #           - scene.kitchen_window_lights_cozy
      #       data:
      #         transition: 5

    default:
      - action: light.turn_off
        target:
          entity_id:
            - light.kitchen_table
            - light.kitchen_island
        data:
          transition: 5
