- alias: "Movement: kitchen"
  id: 7600e21e-5142-4dd0-8439-2fe4416ad473
  trace:
    stored_traces: 10

  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded

    - trigger: state
      id: movement
      entity_id:
        - binary_sensor.motion_kitchen_occupancy
        - binary_sensor.presence_kitchen_occupancy
      from: "off"
      to: "on"

    - trigger: state
      entity_id:
        - binary_sensor.motion_kitchen_occupancy
        - binary_sensor.presence_kitchen_occupancy
      from: "on"
      to: "off"
      for:
        minutes: 1

  condition: []

  action:
    choose:
      - alias: "activate movement mode"
        conditions:
          - alias: "when movement is detected"
            condition: trigger
            id: "movement"

        sequence:
          - alias: "turn on helper"
            action: input_boolean.turn_on
            target:
              entity_id: input_boolean.kitchen_movement

    default:
      - choose:
          conditions:
            - condition: state
              entity_id:
                - binary_sensor.presence_kitchen_occupancy
                - binary_sensor.motion_kitchen_occupancy
              state: "off"
          sequence:
            - alias: "turn off helper"
              action: input_boolean.turn_off
              target:
                entity_id: input_boolean.kitchen_movement
