- alias: "greenhouse: lights"
  id: 7216dadf-1188-4654-b46d-065efd0ad292
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_daylight

  action:
    choose:
      - conditions:
          - condition: state
            # when there is no daylight
            entity_id:
              - input_boolean.house_mode_daylight
            state: "off"

        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id:
                - light.greenhouse_plug

    default:
      - service: homeassistant.turn_off
        target:
          entity_id:
            - light.greenhouse_plug
