- alias: "Hallway downstairs: lights"
  id: 55d4084a-e61b-4e2e-acaf-edc15146b8c8
  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - trigger: state
      entity_id:
        - input_boolean.house_mode_bright_hallway

    - trigger: time
      at:
        - input_datetime.time_goodmorning
        - input_datetime.time_goodnight

    - trigger: state
      id: movement
      entity_id:
        - input_boolean.hallway_downstairs_movement

    - trigger: state
      id: media
      entity_id:
        - media_player.shield_cinema
      to: "playing"

  actions:
    choose:
      - conditions:
          - condition: state
            # when manual mode is on
            entity_id:
              - input_boolean.hallway_downstairs_manual_mode
            state: "on"
        sequence:
          []
          # do nothing

      - conditions:
          - condition: trigger
            id:
              - movement
              - media
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id:
                      - input_boolean.hallway_downstairs_movement
                    state: "on"

                  - condition: state
                    entity_id:
                      - input_boolean.house_mode_bright_hallway
                    state: "off"

                  # - condition: state
                  #   entity_id:
                  #     - input_boolean.house_mode_sleep
                  #   state: "off"

                sequence:
                  - choose:
                      - conditions:
                          - or:
                              - and:
                                  - condition: state
                                    entity_id:
                                      - media_player.shield_cinema
                                    state: "playing"
                                  - condition: time
                                    after: "20:00"
                                    before: "06:00"

                              - condition: time
                                after: "23:00"
                                before: "06:00"
                        sequence:
                          - action: light.turn_on
                            target:
                              entity_id: light.hallen
                            data:
                              brightness: 60
                              transition: 1
                    default:
                      - action: light.turn_on
                        target:
                          entity_id: light.hallen
                        data:
                          brightness: 255
                          transition: 1

            default:
              - action: light.turn_off
                target:
                  entity_id: light.hallen
                data:
                  transition: 5

      - conditions:
          - condition: state
            # when there is daylight
            entity_id:
              - input_boolean.house_mode_bright_hallway
            state: "on"

        sequence:
          - &turn_off # turn off lights
            action: light.turn_off
            target:
              entity_id:
                - light.hallway_downstairs_bench
            data:
              transition: 5

      - conditions:
          - condition: or
            conditions:
              - condition: and
                # turn on lights if
                conditions:
                  - condition: time
                    after: input_datetime.time_goodmorning
                    before: input_datetime.time_goodnight
                  - condition: state
                    entity_id:
                      - input_boolean.house_mode_bright_hallway
                    state: "off"

        sequence:
          - &scene_turn_on
            action: scene.turn_on
            target:
              entity_id:
                - scene.hallway_downstairs_ambience_lights_cozy

    default:
      - *turn_off
