- alias: "Hallway downstairs: lights"
  id: 55d4084a-e61b-4e2e-acaf-edc15146b8c8
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_bright_hallway

    - platform: time
      at:
        - input_datetime.time_goodmorning
        - input_datetime.time_goodnight

    - platform: state
      id: movement
      entity_id:
        - input_boolean.hallway_downstairs_movement

    - platform: state
      id: media
      entity_id:
        - media_player.shield_cinema
      to: "playing"

  action:
    choose:
      - conditions:
          - condition: state
            # when manual mode is on
            entity_id:
              - input_boolean.hallway_downstairs_manual_mode
            state: "on"
        sequence:
          []
          # do nothing

      - conditions:
          - condition: trigger
            id:
              - movement
              - media
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id:
                      - input_boolean.hallway_downstairs_movement
                    state: "on"

                  - condition: state
                    entity_id:
                      - input_boolean.house_mode_bright_hallway
                    state: "off"

                  - condition: state
                    entity_id:
                      - input_boolean.house_mode_sleep
                    state: "off"

                  - condition: time
                    before: "23:00"
                    after: "06:00"

                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id:
                              - media_player.shield_cinema
                            state: "playing"
                        sequence:
                          - service: light.turn_on
                            target:
                              entity_id: light.hallen
                            data:
                              brightness: 60
                              transition: 1
                    default:
                      - service: light.turn_on
                        target:
                          entity_id: light.hallen
                        data:
                          brightness: 255
                          transition: 1

            default:
              - service: light.turn_off
                target:
                  entity_id: light.hallen
                data:
                  transition: 5

      - conditions:
          - condition: state
            # when there is daylight
            entity_id:
              - input_boolean.house_mode_bright_hallway
            state: "on"

        sequence:
          - &turn_off # turn off lights
            service: light.turn_off
            target:
              entity_id:
                - light.hallway_downstairs_bench
            data:
              transition: 5

      - conditions:
          - condition: or
            conditions:
              - condition: and
                # turn on lights if
                conditions:
                  - condition: time
                    # at specific time in the morning
                    after: input_datetime.time_goodmorning
                    # but before a specific time in the evening
                    before: input_datetime.time_goodnight

        sequence:
          - &scene_turn_on
            service: scene.turn_on
            target:
              entity_id:
                - scene.hallway_downstairs_ambience_lights_cozy

    default:
      - *turn_off
