- alias: "Laundry room: lights"
  id: ca853bcb-c701-4090-af6b-0aa888c17562
  trace:
    stored_traces: 25

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      id: movement
      entity_id:
        - input_boolean.laundryroom_movement

    # - platform: state
    #   id: button
    #   entity_id:
    #     - binary_sensor.laundry_room_channel_1_input
    #   from: "off"
    #   to: "on"

  condition: []

  action:
    choose:
      - conditions:
          - condition: trigger
            id: "button"

        sequence:
          - choose:
              - conditions:
                  - alias: "if ceiling light is off"
                    condition: state
                    entity_id:
                      - switch.laundry_room_channel_1
                    state: "off"

                sequence:
                  - &turn_on_ceiling
                    alias: "turn on the lights"
                    service: switch.turn_on
                    target:
                      entity_id: switch.laundry_room_channel_1
                  - &turn_on_bench
                    alias: "turn on bench light"
                    service: light.turn_on
                    target:
                      entity_id: light.laundry_room_bench
                    data:
                      brightness: 50
                      transition: 1

            default:
              - &turn_off
                alias: "turn off the lights"
                service: homeassistant.turn_off
                target:
                  entity_id:
                    - switch.laundry_room_channel_1
                    - light.laundry_room_bench

      - conditions:
          - alias: "turn on lights when entering the room"
            condition: and
            conditions:
              - alias: "if movement detected"
                condition: state
                entity_id:
                  - input_boolean.laundryroom_movement
                state: "on"
              # - alias: "and time is between"
              #   condition: time
              #   after: "07:30:00"
              #   before: "22:00:00"

        sequence:
          - choose:
              - conditions:
                  - alias: "if time is between"
                    condition: time
                    after: "07:30:00"
                    before: "22:00:00"

                sequence:
                  - *turn_on_ceiling
                  - *turn_on_bench

            default:
              - *turn_on_bench

    default:
      - *turn_off
