- alias: "Entre: lights"
  id: 2467611a-12d7-4a8d-8650-e18e25e5082b
  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - trigger: state
      entity_id:
        - input_boolean.house_mode_daylight
        - input_boolean.house_mode_outside_work

    - trigger: state
      id: movement
      entity_id: input_boolean.front_movement
      from: "off"
      to: "on"

    - trigger: state
      id: movement_off
      entity_id: input_boolean.front_movement
      from: "on"
      to: "off"

  actions:
    choose:
      - alias: "activate outdoor work mode"
        conditions:
          - alias: "when outside work mode is on"
            condition: state
            entity_id:
              - input_boolean.house_mode_outside_work
            state: "on"

        sequence:
          - alias: "activate outside work scene"
            action: scene.turn_on
            target:
              entity_id: scene.outdoor_work_entre
            data:
              transition: 2

      - conditions:
          - condition: trigger
            # if triggered by movement
            id: "movement"
          - condition: state
            # and turned on (by daylight off)
            entity_id:
              - light.entre
            state: "on"

        sequence:
          # illuminate for a while and return to previous mode
          - action: scene.turn_on
            target:
              entity_id: scene.outdoor_entre_movement
            data:
              transition: 2

      - conditions:
          condition: state
          # if not daylight
          entity_id:
            - input_boolean.house_mode_daylight
          state: "off"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.outdoor_entre_lights_default
            data:
              transition: 5

    default:
      - action: light.turn_off
        target:
          entity_id: light.entre
        data:
          transition: 5
