- alias: "Livingroom: lights"
  id: 426174fb-2fc8-41e3-8e92-62f37ef26c54
  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - trigger: state
      entity_id:
        - input_boolean.house_mode_bright_inside

    # - platform: state
    #   id: remote
    #   entity_id:
    #     - sensor.livingroom_remote_action
    - trigger: state
      entity_id: event.livingroom_remote_action
      not_from: unavailable
      id: remote

    - trigger: state
      id: night_or_away
      entity_id:
        - input_boolean.house_mode_sleep
        - input_boolean.house_mode_away
      from: "off"
      to: "on"

    - trigger: time
      at:
        - input_datetime.time_goodmorning
        - input_datetime.time_goodnight

  actions:
    choose:
      - conditions:
          - condition: trigger
            id: "remote"

        sequence:
          - variables:
              #action: "{{ trigger.to_state.state }}"
              action: "{{ trigger.to_state.attributes.event_type }}"

          - choose:
              - conditions: "{{ action == 'on' }}"
                sequence:
                  - action: light.toggle
                    target:
                      entity_id: light.livingroom_front_1

              - conditions: "{{ action == 'off' }}"
                sequence:
                  - action: light.toggle
                    target:
                      entity_id: light.livingroom_back_3

              - conditions: "{{ action == 'brightness_move_up' }}"
                sequence:
                  - action: light.toggle
                    target:
                      entity_id: light.vardagsrum_framre

              - conditions: "{{ action == 'brightness_move_down' }}"
                sequence:
                  - action: light.toggle
                    target:
                      entity_id: light.vardagsrum_bakre

            default:
              - delay:
                  milliseconds: 1

      - conditions:
          - condition: trigger
            # when night mode is active
            id: night_or_away
        sequence:
          - action: light.turn_off
            # turn of regular lights
            target:
              entity_id:
                - light.vardagsrum_framre
                - light.vardagsrum_bakre
                - light.floor_lamp

      - conditions:
          - condition: or
            conditions:
              - condition: and
                # turn on lights if
                conditions:
                  - condition: time
                    # at specific time in the morning
                    after: input_datetime.time_goodmorning
                    # but before a specific time in the evening
                    before: input_datetime.time_goodnight
                  - condition: state
                    # when it's dark inside
                    entity_id:
                      - input_boolean.house_mode_bright_inside
                    state: "off"

        sequence:
          - &scene_turn_on
            action: scene.turn_on
            target:
              entity_id:
                - scene.livingroom_ambience_lights_cozy
                - scene.livingroom_window_lights_cozy
            data:
              transition: 5

      - conditions:
          - condition: state
            # when there is daylight
            entity_id:
              - input_boolean.house_mode_bright_inside
            state: "on"

        sequence:
          - &turn_off # turn off lights
            action: light.turn_off
            target:
              entity_id:
                - light.floor_lamp
                - light.livingroom_window_1
            data:
              transition: 5

    default:
      - *turn_off
