- alias: "Livingroom: lights"
  id: 426174fb-2fc8-41e3-8e92-62f37ef26c54
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_bright_inside

    - platform: event
      event_type: deconz_event
      event_data:
        id: "livingroom_remote"
      id: remote

    - platform: state
      id: night
      entity_id:
        - input_boolean.house_mode_sleep
      from: "off"
      to: "on"

    - platform: time
      at:
        - input_datetime.time_goodmorning
        - input_datetime.time_goodnight


  action:
    choose:
      - conditions:
          - condition: trigger
            id: "remote"

        sequence:
          - choose:
            - conditions: '{{ trigger.event.data.event == 1002 }}'
              sequence:
                - service: light.toggle
                  target:
                    entity_id: light.livingroom_front_1

            - conditions: '{{ trigger.event.data.event == 2002 }}'
              sequence:
                - service: light.toggle
                  target:
                    entity_id: light.livingroom_back_3

            - conditions: '{{ trigger.event.data.event == 1001 }}'
              sequence:
                - service: light.toggle
                  target:
                    entity_id: light.vardagsrum_framre

            - conditions: '{{ trigger.event.data.event == 2001 }}'
              sequence:
                - service: light.toggle
                  target:
                    entity_id: light.vardagsrum_bakre

            default:
              - delay:
                  milliseconds: 1
        
      - conditions:
          - condition: trigger
            # when night mode is active
            id: night
        sequence:
          - service: light.turn_off
            # turn of regular lights
            target:
              entity_id:
                - light.vardagsrum_framre
                - light.vardagsrum_bakre

      - conditions:
          - condition: or
            conditions:
              - condition: and
                # turn on lights if
                conditions:
                  - condition: time
                    # at specific time in the morning
                    after: input_datetime.time_goodmorning
                    # but before a specific time in the evening
                    before: input_datetime.time_goodnight

        sequence:
          - &scene_turn_on
            service: scene.turn_on
            target:
              entity_id:
                - scene.livingroom_ambience_lights_cozy
                - scene.livingroom_window_lights_cozy
            data:
              transition: 5
              
      - conditions:
          - condition: state
            # when there is daylight
            entity_id:
              - input_boolean.house_mode_bright_inside
            state: "on"

        sequence:
          - &turn_off # turn off lights
            service: light.turn_off
            target:
              entity_id:
                - light.floor_lamp
                - light.livingroom_window_1
            data:
              transition: 5

    default:
      - *turn_off
