- alias: "Garage: handle stereo"
  id: 7edf8e18-0ec4-44cb-9d03-dc49c0fd7a0c
  mode: queued

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type: automation_reloaded

    - platform: state
      entity_id:
        - binary_sensor.garage_port

    - platform: state
      id: no_motion
      entity_id: binary_sensor.motion_garage_presence
      from: "on"
      to: "off"
      for:
        minutes: &nomotion 15

  condition: []

  action:
    - choose:
        - conditions:
            - alias: "if the port is open"
              condition: state
              entity_id:
                - binary_sensor.garage_port
              state: "on"

          sequence:
            - alias: "turn on the stereo"
              service: switch.turn_on
              target:
                entity_id: switch.garage_plug


        - conditions:
            - alias: "if the port is closed"
              condition: state
              entity_id:
                - binary_sensor.garage_port
              state: "off"

            - alias: "and no motion has been detected for a while"
              condition: state
              entity_id: binary_sensor.motion_garage_presence
              state: "off"
              for:
                minutes: *nomotion

          sequence:
            - alias: "turn off the stereo"
              service: switch.turn_off
              target:
                entity_id: switch.garage_plug
