- alias: "Terrace: lights"
  id: 3b25b5a0-8281-4d08-b624-aa37eaa7db56
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_daylight

  action:
    choose:
      - conditions:
          - condition: state
            # when it's dark outside
            entity_id:
              - input_boolean.house_mode_daylight
            state: "off"

        sequence:
          - &scene_turn_on
            service: light.turn_on
            target:
              entity_id:
                - light.wled_terrace
            data:
              transition: 5
      - conditions:
          - condition: state
            # when there is daylight
            entity_id:
              - input_boolean.house_mode_daylight
            state: "on"

        sequence:
          - &turn_off # turn off lights
            service: light.turn_off
            target:
              entity_id:
                - light.wled_terrace
            data:
              transition: 5

    default:
      - *turn_off
