- alias: "Hallway upstairs: lights"
  id: 009d2374-2031-4d2d-b19d-349a5ac5c52f
  mode: queued
  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - trigger: state
      entity_id:
        - input_boolean.house_mode_bright_inside

    - trigger: time
      at:
        - input_datetime.time_goodmorning
        - input_datetime.time_goodnight

    - trigger: state
      id: "no_movement"
      entity_id:
        - binary_sensor.motion_hallway_upstairs_occupancy
      from: "on"
      to: "off"
      for:
        minutes: "{{ states('input_number.hallway_upstairs_timeout')|int }}"

    - trigger: state
      id: night_or_away
      entity_id:
        - input_boolean.house_mode_sleep
        - input_boolean.house_mode_away
      from: "off"
      to: "on"

    # - platform: state
    #   id: remote
    #   entity_id:
    #     - sensor.remote_hallway_upstairs_1_action
    - trigger: state
      entity_id: event.remote_hallway_upstairs_1_action
      not_from: unavailable
      id: remote

  actions:
    choose:
      - conditions:
          - condition: trigger
            id: remote
        sequence:
          - variables:
              #action: "{{ trigger.to_state.state }}"
              action: "{{ trigger.to_state.attributes.event_type }}"

          - choose:
              - alias: "on pressed"
                conditions: "{{ action in ['on'] }}"
                sequence:
                  - choose:
                      - conditions: "{{ states('light.hallway_upstairs_2') == 'off' }}"
                        sequence:
                          - action: light.turn_on
                            target:
                              entity_id:
                                - light.hallway_upstairs_2
                            data:
                              brightness: 255
                    default:
                      - action: light.turn_off
                        target:
                          entity_id:
                            - light.hallway_upstairs_2

              - alias: "off pressed"
                conditions: "{{ action in ['off'] }}"
                sequence:
                  - choose:
                      - conditions: "{{ states('light.hallway_upstairs_1') == 'off' }}"
                        sequence:
                          - action: light.turn_on
                            target:
                              entity_id:
                                - light.hallway_upstairs_1
                            data:
                              brightness: 255
                    default:
                      - action: light.turn_off
                        target:
                          entity_id:
                            - light.hallway_upstairs_1

      - conditions:
          - condition: trigger
            id:
              - "no_movement"
              - "night_or_away"
        sequence:
          - &turn_off_ceiling
            action: light.turn_off
            target:
              entity_id:
                - light.hallway_upstairs_1
                - light.hallway_upstairs_2
            data:
              transition: 5

      - conditions:
          - condition: state
            # when there is daylight
            entity_id:
              - input_boolean.house_mode_bright_inside
            state: "on"

        sequence:
          - &turn_off_window # turn off lights
            action: light.turn_off
            target:
              entity_id:
                - light.hallway_upstairs_window
            data:
              transition: 5

      - conditions:
          - condition: or
            conditions:
              - condition: and
                # turn on lights if
                conditions:
                  - condition: time
                    # at specific time in the morning
                    after: input_datetime.time_goodmorning
                    # but before a specific time in the evening
                    before: input_datetime.time_goodnight

        sequence:
          - &scene_turn_on
            action: scene.turn_on
            target:
              entity_id:
                - scene.hallway_upstairs_window_lights_cozy

    default:
      - *turn_off_window
