- alias: "Hallway upstairs: lights"
  id: 009d2374-2031-4d2d-b19d-349a5ac5c52f
  mode: queued
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_bright_inside

    - platform: time
      at:
        - input_datetime.time_goodmorning
        - input_datetime.time_goodnight

    - platform: state
      id: "no_movement"
      entity_id:
        - binary_sensor.motion_hallway_upstairs_occupancy
      from: "on"
      to: "off"
      for:
        minutes: 5

    - platform: state
      id: night_or_away
      entity_id:
        - input_boolean.house_mode_sleep
        - input_boolean.house_mode_away
      from: "off"
      to: "on"

    - platform: state
      id: remote
      entity_id:
        - sensor.remote_hallway_upstairs_1_action

  action:
    choose:
      - conditions:
          - condition: trigger
            id: remote
        sequence:
          - variables:
              action: "{{ trigger.to_state.state }}"

          - choose:
              - alias: "on pressed"
                conditions: "{{ action in ['on'] }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id:
                        - light.hallway_upstairs_2

              - alias: "off pressed"
                conditions: "{{ action in ['off'] }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: light.hallway_upstairs_1

      - conditions:
          - condition: trigger
            id:
              - "no_movement"
              - "night_or_away"
        sequence:
          - &turn_off_ceiling
            service: light.turn_off
            target:
              entity_id:
                - light.hallen_uppe
            data:
              transition: 5

      - conditions:
          - condition: state
            # when there is daylight
            entity_id:
              - input_boolean.house_mode_bright_inside
            state: "on"

        sequence:
          - &turn_off_window # turn off lights
            service: light.turn_off
            target:
              entity_id:
                - light.hallway_upstairs_window
            data:
              transition: 5

      - conditions:
          - condition: or
            conditions:
              - condition: and
                # turn on lights if
                conditions:
                  - condition: time
                    # at specific time in the morning
                    after: input_datetime.time_goodmorning
                    # but before a specific time in the evening
                    before: input_datetime.time_goodnight

        sequence:
          - &scene_turn_on
            service: scene.turn_on
            target:
              entity_id:
                - scene.hallway_upstairs_window_lights_cozy

    default:
      - *turn_off_window
