- alias: "Bedroom: lights"
  id: 48d8b685-cc44-4b54-bf1b-bbaf4a088413
  trace:
    stored_traces: 25

  triggers:
    - trigger: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - trigger: state
      entity_id:
        - event.bedroom_remote_right_action
        - event.bedroom_remote_left_action
        - event.bedroom_remote_wall_action
      not_from: unavailable
      id: remote

    - trigger: state
      entity_id:
        - input_boolean.house_mode_away
        - input_boolean.house_mode_sleep
        - input_boolean.house_mode_bright_inside
        - input_boolean.bedroom_nightlight

    - trigger: state
      id: auto_off
      entity_id:
        - binary_sensor.presence_bedroom_occupancy
      to: "off"
      for:
        minutes: 10

    - trigger: time
      id: reset
      at:
        - input_datetime.house_reset_settings
        - input_datetime.house_reset_settings_day

    - trigger: time
      id: wakeup
      at: input_datetime.wakeup_time

    - trigger: time
      id: goodnight
      at:
        - input_datetime.time_goodnight

  actions:
    - choose:
        - conditions:
            - condition: trigger
              id: auto_off
          sequence:
            - choose:
                - conditions:
                    - condition: state
                      entity_id:
                        - light.bedroom_ceiling
                      state: "on"
                  sequence:
                    - action: light.turn_off
                      target:
                        entity_id: light.bedroom_ceiling
                      data:
                        transition: 5

        - conditions:
            # when a remote button is pressed
            - condition: trigger
              id: "remote"

          sequence:
            - variables:
                action: "{{ trigger.to_state.attributes.event_type }}"

            - alias: "Remote buttons"
              choose:
                - alias: "Big bulb pressed"
                  conditions: "{{ action in ['big-press', 'on', 'brightness_up_click'] }}"
                  sequence:
                    - choose:
                        - conditions:
                            - alias: "if ceiling light is off"
                              condition: state
                              entity_id:
                                - light.bedroom_ceiling
                              state: "off"

                          sequence:
                            - alias: "turn on ceiling light"
                              action: light.turn_on
                              target:
                                entity_id: light.bedroom_ceiling
                              data:
                                brightness: 255

                      default:
                        - alias: "turn off ceiling light"
                          action: light.turn_off
                          target:
                            entity_id: light.bedroom_ceiling

                - alias: "Small bulb pressed"
                  conditions: "{{ action in ['small-press', 'off', 'brightness_down_click'] }}"
                  sequence:
                    - alias: "toggle ambience lights"
                      action: light.toggle
                      target:
                        entity_id: >
                          {{ 
                            expand(area_entities("bedroom") 
                            | select('match', 'light')) 
                            | selectattr('entity_id', 'in', label_entities('ambience')) 
                            | map(attribute='entity_id')
                            | list 
                          }}
                - alias: "Left pressed"
                  conditions: "{{ action in ['left-press', 'arrow_left_click'] }}"
                  sequence:
                    - alias: "toggle left bed lamp"
                      action: light.toggle
                      target:
                        entity_id: light.bedroom_left

                - alias: "Right pressed"
                  conditions: "{{ action in ['right-press', 'arrow_right_click'] }}"
                  sequence:
                    - alias: "toggle right bed lamp"
                      action: light.toggle
                      target:
                        entity_id: light.bedroom_right

                - alias: "Small bulb press hold"
                  conditions: "{{ action in ['small-hold', 'brightness_move_down'] }}"
                  sequence:
                    - alias: "turn off ambience"
                      action: light.turn_off
                      target:
                        entity_id: >
                          {{ 
                            expand(area_entities("bedroom") 
                            | select('match', 'light')) 
                            | selectattr('entity_id', 'in', label_entities('ambience')) 
                            | map(attribute='entity_id')
                            | list 
                          }}
        - conditions:
            # turn off ambience light
            - condition: trigger
              # when it's late
              id: goodnight
          sequence:
            - alias: "if night light mode is off"
              choose:
                conditions: "{{ states('input_boolean.bedroom_nightlight') == 'off' }}"
                sequence:
                  # turn off lights
                  - action: light.turn_off
                    target:
                      area_id: bedroom
                      label_id: ambience
                    data:
                      transition: 5
