- alias: "bedroom lights"
  id: 48d8b685-cc44-4b54-bf1b-bbaf4a088413
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded
    
    - platform: event
      id: remote
      event_type: deconz_event
      event_data:
        id: tradfri_on_off_switch

    - platform: event
      id: remote
      event_type: deconz_event
      event_data:
        id: bedroom_remote_1

    - platform: event
      id: remote
      event_type: deconz_event
      event_data:
        id: bedroom_remote_2

    - platform: state
      entity_id:
        - input_boolean.house_mode_away
        - input_boolean.house_mode_sleep
        
    - platform: state
      id: lights
      entity_id:
        - light.bedroom_ceiling
        - light.bedroom_left
        - light.bedroom_right
        - light.hallway_upstairs_wall
    
    - platform: time
      id: reset
      at: input_datetime.house_reset_settings

  action:
    - choose:
      - alias: "Reset manual mode before morning"
        conditions:
          - alias: "Triggered by defined time"
            condition: trigger
            id: "reset"
        
        sequence:
          - &turn_off_manual_mode
            alias: "Reset manual mode"
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.bedroom_manual_mode
      
      - alias: "Turn off when sleep or away"
        conditions:
          - condition: or
            conditions:
              - alias: "When away"
                condition: state
                entity_id: input_boolean.house_mode_away
                state: "on"
              
              - alias: "When sleeping"
                condition: state
                entity_id: input_boolean.house_mode_sleep
                state: "on"
        
        sequence:
          - *turn_off_manual_mode
          - &turn_off
            alias: "Turn off lights"
            service: light.turn_off
            target:
              area_id: "{{ area_id('Sovrummet') }}"
            data:
              transition: 5


      - alias: "Bedroom remote was used"
        conditions:
          - alias: "When triggered by bedroom remote"
            condition: trigger
            id: "remote"

        sequence:
          - variables:
              action: "{{ trigger.event.data.event }}"

          - alias: "Remote buttons"
            choose:
              - alias: "Big bulb pressed"
                conditions: "{{ action == 1002 }}"
                sequence:
                  - alias: "toggle ceiling light"
                    service: light.toggle
                    target:
                      entity_id: light.bedroom_ceiling

                  - &turn_on_manual_mode
                    alias: "Turn on manual mode"
                    service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.bedroom_manual_mode

              - alias: "Small bulb pressed"
                conditions: "{{ action == 2002 }}"
                sequence:
                  - *turn_on_manual_mode
                  - alias: "toggle wall lamp"
                    service: light.toggle
                    target:
                      entity_id: light.hallway_upstairs_wall

              - alias: "Left pressed"
                conditions: "{{ action == 3002 }}"
                sequence:
                  - *turn_on_manual_mode
                  - alias: "toggle left bed lamp"
                    service: light.toggle
                    target:
                      entity_id: light.bedroom_left

              - alias: "Right pressed"
                conditions: "{{ action == 4002 }}"
                sequence:
                  - *turn_on_manual_mode
                  - alias: "toggle right bed lamp"
                    service: light.toggle
                    target:
                      entity_id: light.bedroom_right

              - alias: "Big/small bulb press hold"
                conditions: "{{ action in [1001, 2001] }}"
                sequence:
                  - *turn_on_manual_mode
                  - alias: "determen direction"
                    variables:
                      step: "{{ 50 if action == 1001 else -50 }}"
                  
                  - alias: "Change brightness"
                    service: light.turn_on
                    target:
                      entity_id: light.bedroom_ceiling
                    data:
                      brightness_step: "{{ step }}"
                      transition: 1
      
      - alias: "Do nothing when manual mode is on"
        conditions:
          - alias: "When manual mode is on"
            condition: state
            entity_id: input_boolean.bedroom_manual_mode
            state: "on"
        
        sequence: []
      
      - alias: "Manual action detected"
        conditions:
          - alias: "One of the lights changed state"
            condition: trigger
            id: "lights"
          
          - alias: "It was by a user"
            condition: template
            value_template: "{{ trigger.to_state.context.user_id != None }}"

        sequence:
          - *turn_on_manual_mode

      default:
        - *turn_off




