- platform: template
  sensors:
    electricity_price_total:
      friendly_name: "Elpris"
      value_template: >-
        {% set transfer = 0.667 %}
        {% set price = 0.6366 %}
        {% set total = (states('sensor.electricity_price_galevagen_5')|float(default=0) + transfer) %}
        {% set total = price + transfer %}
        {{ total | round(3) }}
      unit_of_measurement: "SEK/kWh"