- platform: min_max
  unique_id: af11efcd-b689-47a9-ae89-4023a9e8c570
  name: outdoor_illuminance_mean
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.motion_front_illuminance
    - sensor.motion_driveway_illuminance
    - sensor.motion_barn_illuminance

- platform: min_max
  unique_id: ee470db9-b4fd-4d96-ba6e-58530ee3e73c
  name: outdoor_illuminance_median
  type: median
  round_digits: 0
  entity_ids:
    - sensor.motion_front_illuminance
    - sensor.motion_driveway_illuminance
    - sensor.motion_barn_illuminance

- platform: min_max
  unique_id: 192421cf-0a72-4c33-b0f6-75b87666ecee
  name: outdoor_illuminance_min
  type: min
  round_digits: 0
  entity_ids:
    - sensor.motion_front_illuminance
    - sensor.motion_driveway_illuminance
    - sensor.motion_barn_illuminance
