- platform: integration
  name: reimann_fuse20_energy
  method: left
  source: sensor.export_power_below_20a
  unit_prefix: k

- platform: integration
  name: reimann_fuse25_energy
  method: left
  source: sensor.export_power_above_20a
  unit_prefix: k
