- platform: rest
  unique_id: c72031bc-69e0-45c8-a084-db8f97b4ba8e
  resource: !secret mealie_url_day
  method: GET
  name: Mealie dagens middag
  headers:
    Authorization: !secret mealie_token
  #value_template: "{{ value_json.name }}"
  value_template: >
    {% if value_json[0] is defined and value_json[0].recipe is defined and value_json[0].recipe.name is defined %}
      {{ value_json[0].recipe.name }}
    {% else %}
      inget planerat
    {% endif %}

  json_attributes_path: $..recipe
  json_attributes:
    - name
    - id
    - totalTime
    - prepTime
    - performTime


# - platform: rest
#   resource: !secret mealie_url_week
#   method: GET
#   name: Mealie veckans meny
#   headers:
#     Authorization: !secret mealie_token
