- platform: rest
  # unique_id: c72031bc-69e0-45c8-a084-db8f97b4ba8e
  resource: !secret mealie_url_day
  method: GET
  name: Mealie dagens middag
  headers:
    Authorization: !secret mealie_token
  #value_template: "{{ value_json.name }}"
  value_template: >
    {% if value_json[0] is defined and value_json[0].recipe is defined and value_json[0].recipe.name is defined %}
      {"name":"{{value_json[0].recipe.name}}","id":"{{value_json[0].recipe.id}}"}
    {% else %}
      {"name":"inget planerat","id":""}
    {% endif %}

