# filter out ridiculous amount of sensor updates (and smooth things out)
#
- platform: filter
  name: "hobbyroom_outlet_channel_1_power"
  unique_id: 753230da-a7d4-4290-a4a1-5c7d9438de3e
  entity_id: sensor.hobbyroom_outlet_channel_1_power_tmp
  filters:
    - filter: time_simple_moving_average
      window_size: "00:01"
      precision: 0
      
- platform: filter
  name: "hobbyroom_outlet_channel_2_power"
  unique_id: d338b76c-8adb-4e4d-8790-e5159c927741
  entity_id: sensor.hobbyroom_outlet_channel_2_power_tmp
  filters:
    - filter: time_simple_moving_average
      window_size: "00:01"
      precision: 0

