# filter out ridiculous amount of sensor updates (and smooth things out)
#
- platform: filter
  name: "hobbyroom_outlet_channel_1_power"
  unique_id: 753230da-a7d4-4290-a4a1-5c7d9438de3e
  entity_id: sensor.hobbyroom_outlet_channel_1_power_tmp
  filters:
    - filter: outlier
      window_size: 10
      radius: 6.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: "00:01"
      precision: 0

- platform: filter
  name: "hobbyroom_outlet_channel_2_power"
  unique_id: d338b76c-8adb-4e4d-8790-e5159c927741
  entity_id: sensor.hobbyroom_outlet_channel_2_power_tmp
  filters:
    - filter: time_simple_moving_average
      window_size: "00:01"
      precision: 0

- platform: filter
  name: "shelly_dishwasher_power"
  unique_id: 2de5d7de-86fa-40fb-915e-cd43c101d025
  entity_id: sensor.shelly_dishwasher_power_tmp
  filters:
    - filter: time_simple_moving_average
      window_size: "00:01"
      precision: 0
