- platform: influxdb
  username: !secret influx_user
  password: !secret influx_pass
  database: !secret influx_grid_db
  queries:
    - name: statnett_prod_se_nuclear
      unique_id: af27fa16-2d8e-403c-81e8-ebd4af7796cf
      measurement: MW
      where: '"zone" = ''SE'''
      group_function: last
      field: "nuclear"
      
    - name: statnett_prod_se_wind
      unique_id: 31e09ebe-f58e-493e-8ac4-01b60eac5d44
      measurement: MW
      where: '"zone" = ''SE'''
      group_function: last
      field: "wind"

