- platform: min_max
  name: outdoor_min_max
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.outdoor_north_temperature
    - sensor.outdoor_south_temperature
    - sensor.outdoor_east_temperature
    - sensor.outdoor_west_temperature

- platform: min_max
  name: outdoor_median
  type: median
  round_digits: 1
  entity_ids:
    - sensor.outdoor_north_temperature
    - sensor.outdoor_south_temperature
    - sensor.outdoor_east_temperature
    - sensor.outdoor_west_temperature
  
  