# Sensors for common network information
#
platform: wifi_info
ip_address:
  name: "IP Address"
  icon: mdi:ip-network
mac_address:
  name: "MAC Address"
ssid:
  name: "SSID"
  icon: mdi:wifi-settings
bssid:
  name: "BSSID"
  id: wifi_bssid
  icon: mdi:identifier
  on_value:
    then:
      - component.update: wifi_access_point
