- alias: "eHub: system state"
  id: e0e5220c-f753-4adb-9a48-d574928ada9c
  mode: queued
  trace:
    stored_traces: 10

  trigger:
    - platform: state
      entity_id:
        - sensor.ferroamp_xl28_system_state
      not_from:
        - "none"
        - "unknown"
        - "unavailable"
      not_to:
        - "none"
        - "unknown"
        - "unavailable"

  action:
    choose:
      - conditions: "{{ trigger.to_state.state|int > 0 }}"
        sequence:
          - service: notify.castle_log
            data:
              title: Ferroamp
              message: >
                {% set e = trigger.to_state.state|string %}
                {% set x = ('0x'+e)|int(base=16, default=0) %}
                {% set v = 1 %}
                {% set f = namespace(ecodes=[])%}
                {% for i in range(0,100) %}
                  {% set v = (2**i) %}
                  {% if x|bitwise_and(v) == v %}
                    {% set f.ecodes = f.ecodes + [i+1] %}
                  {% endif %}
                {% endfor %}
                {{trigger.to_state.name}}: {{trigger.to_state.state}} ({{f.ecodes}})

    default:
      - service: notify.castle_log
        data:
          title: Ferroamp
          message: >
            {{trigger.to_state.name}} rapporterar state '0'
