- alias: "SSO: faultcode"
  id: 46d44938-1a8c-43df-9ef5-9d36d424bb95
  mode: queued
  trace:
    stored_traces: 10

  trigger:
    - platform: state
      entity_id:
        - sensor.ferroamp_xl28_sso_22010644_faultcode
        - sensor.ferroamp_xl28_sso_21090039_faultcode
        - sensor.ferroamp_xl28_sso_21090135_faultcode
        - sensor.ferroamp_xl28_sso_21090071_faultcode
      not_from:
        - "none"
        - "unknown"
        - "unavailable"
      not_to:
        - "none"
        - "unknown"
        - "unavailable"
      
  action:
    choose:
      - conditions: "{{ trigger.to_state.state|int > 0 }}"
        sequence:
          - service: notify.castle_log
            data:
              title: Ferroamp
              message: >
                {% set f = namespace(errors=[]) %}
                {% for a in trigger.to_state.attributes|reject('in', ['icon', 'friendly_name']) %}
                    {% set f.errors = f.errors + [trigger.to_state.attributes[a]] %}
                {% endfor %}
                {{trigger.to_state.name}} rapporterar felkod: {{trigger.to_state.state}} ({{f.errors|join(', ')}})

    default:
      - service: notify.castle_log
        data:
          title: Ferroamp
          message: >
            {{trigger.to_state.name}} rapporterar normalt läge igen
