- alias: "Techroom: ups changed status"
  id: 811aa378-4a4e-4b52-a63f-ed63ea9a4172
  mode: queued
  trace:
    stored_traces: 10

  triggers:
    - trigger: state
      entity_id: sensor.techups_status
      not_to:
        - "unknown"
        - "unavailable"
      not_from:
        - "unknown"
        - "unavailable"

  actions:
    - action: notify.castle
      data:
        title: "UPS teknikrum"
        message: "Status: {{states('sensor.techups_status')}}"
