- alias: "Freezer temperature alarm"
  id: e473c7d9-772e-4084-a3aa-9ad6b20781d7
  triggers:
    - trigger: numeric_state
      entity_id:
        # - sensor.freezer_kitchen_temperature
        - sensor.laundry_freezer_temperature
        - sensor.garage_freezer_temperature
      above: -15
      for:
        minutes: 1
  actions:
    - action: notify.family
      data_template:
        title: "Frysen"
        message: >
          {% set mapper =  {
            'sensor.freezer_kitchen_temperature' : 'frysen i köket',
            'sensor.laundry_freezer_temperature' : 'frysen i tvättstugan',
            'sensor.garage_freezer_temperature' : 'frysen i garaget'
          } %}
          "För hög temperatur i {{ mapper[trigger.entity_id] }}! ({{ trigger.to_state.state }}C)"
        data:
          tag: freezer
          sticky: true

- alias: "Freezer critical temperature alarm"
  id: 434a2b9a-4da7-4bd2-9229-b755ce7d3379
  triggers:
    - trigger: numeric_state
      entity_id:
        # - sensor.freezer_kitchen_temperature
        - sensor.laundry_freezer_temperature
        - sensor.garage_freezer_temperature
      above: -10
      for:
        minutes: 1
  actions:
    - repeat:
        while:
          - condition: template
            value_template: "{{ trigger.to_state.state > -10 }}"
        sequence:
          - action: notify.family
            data_template:
              title: "Frysen kritisk!"
              message: >
                {% set mapper =  {
                  'sensor.freezer_kitchen_temperature' : 'frysen i köket',
                  'sensor.laundry_freezer_temperature' : 'frysen i tvättstugan',
                  'sensor.garage_freezer_temperature' : 'frysen i garaget'
                } %}
                "Kritisk temperatur i {{ mapper[trigger.entity_id] }}! ({{ trigger.to_state.state }}C)"
              data:
                tag: freezer
                sticky: true
                ttl: 0
                priority: high
                channel: alarm_stream
          - delay:
              minutes: 15
