- alias: "Indoor ligts: turn on in the morning"
  id: c073f007-09d7-4fc7-b749-3b39bbad60de
  trigger:
    platform: time
    at: '06:00'
  condition:
    condition: sun
    before: sunrise
  action:
    - service: light.turn_on
      target:
        entity_id:
        - light.hallway_upstairs_wall
      data:
        brightness: 1
        


- alias: "Indoor lights: turn off at sunrise"
  id: 03cc22b2-c269-4842-855a-0c28558a9886
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: time
    after: '06:00'
  action:
    - service: light.turn_off
      target:
        entity_id:
        - light.innelampor

- alias: "Indoor lights: turn off at sunset"
  id: 75470e48-9bd8-472f-b3f5-8834ff2d6833
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: time
    before: '23:30'
  action:
    - service: light.turn_on
      target:
        entity_id: 
          - light.innelampor
      data:
        brightness: 255

- alias: "Indoor lights: turn off at night"
  id: be207a50-3dce-478d-bf0e-14c5e2c941eb
  trigger:
    platform: time
    at: '23:30'
  action:
    - service: light.turn_off
      target:
        entity_id: 
          - light.innelampor