- alias: "Flash some lights on driveway motion"
  id: 63fe107f-06f0-44ad-b430-e2ff493272f7
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_driveway_occupancy
      from: "off"
      to: "on"

  action:
    - alias: "when motion detected"
      choose:
        - conditions:
            condition: state
            entity_id:
              - input_boolean.house_mode_daylight
            state: "on"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.floor_lamp
            - delay:
                seconds: 2
            - service: light.turn_off
              target:
                entity_id: light.floor_lamp

        - conditions:
            condition: state
            entity_id:
              - input_boolean.house_mode_daylight
            state: "off"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.floor_lamp
            - delay:
                seconds: 2
            - service: scene.turn_on
              target:
                entity_id: scene.livingroom_ambience_lights_cozy
              data:
                transition: 1

    # - service: scene.create
    #   data:
    #     scene_id: notify_lights_before
    #     snapshot_entities:
    #       - light.floor_lamp
    # - service: light.turn_on
    #   target:
    #     entity_id: light.floor_lamp
    #   data:
    #     brightness: 255
    #     #transition: 0
    # - repeat:
    #     while:
    #     - condition: template
    #       value_template: "{{ repeat.index < 2 }}"
    #     sequence:
    #     - delay:
    #         seconds: 2
    #     - service: light.turn_on
    #       target:
    #         entity_id: light.floor_lamp
    #       data:
    #         brightness: 50
    #         #transition: 0
    #     - delay:
    #         seconds: 2
    #     - service: light.turn_on
    #       target:
    #         entity_id: light.floor_lamp
    #       data:
    #         brightness: 255
    #         #transition: 0
    # - delay:
    #     seconds: 2
    # - service: scene.turn_on
    #   target:
    #     entity_id: scene.notify_lights_before
