- alias: "test multiple remotes"
  id: 64070baf-8273-4617-b223-4295f9e1db5b
  trigger:
    # - platform: event
    #   id: remote
    #   event_type: deconz_event
    #   event_data:
    #     id: tradfri_remote_control

    - platform: state
      id: remote
      entity_id: sensor.fjarren
      to:
        - right-press


  action:
    # - service: light.toggle
    #   target:
    #     entity_id: light.floor_lamp
      # data:
      #   transition: 0
      #   flash: short
    # - choose:
    #   - alias: "remote was used"
    #     conditions:
    #       - alias: "when triggered"
    #         condition: trigger
    #         id: "remote"
        
    #     sequence:
    #       - alias: "toggle a light"
    #         service: light.toggle
    #         target:
    #           entity_id: light.floor_lamp