- alias: "test multiple remotes"
  id: 64070baf-8273-4617-b223-4295f9e1db5b
  mode: queued
  trace:
    stored_traces: 20
  trigger:
    # - platform: event
    #   id: remote
    #   event_type: deconz_event
    #   event_data:
    #     id: tradfri_remote_control
    - platform: time_pattern
      hours: '*'


    - platform: state
      id: remote
      entity_id: sensor.bedroom_remote_wall_action


  action:
    - service: system_log.write
      data:
        message: "trigger: {{ trigger }}"
    # - service: light.toggle
    #   target:
    #     entity_id: light.floor_lamp
      # data:
      #   transition: 0
      #   flash: short
    # - choose:
    #   - alias: "remote was used"
    #     conditions:
    #       - alias: "when triggered"
    #         condition: trigger
    #         id: "remote"
        
    #     sequence:
    #       - alias: "toggle a light"
    #         service: light.toggle
    #         target:
    #           entity_id: light.floor_lamp


# - alias: test2
#   id: de2741d2-72c0-4f96-b7dc-39583739c125
#   mode: queued
#   trace:
#     stored_traces: 20
#   trigger:
#     - platform: time
#       at: 
#         entity_id: input_datetime.house_test_time
#         offset: -00:30:00

#   action:
#     - service: system_log.write
#       data:
#         message: "boop: {{ trigger }}"

# - alias: "detect atmos"
#   trigger:
#     - platform: state
#       entity_id: media_player.onkyo
#       attribute: format

#   action:
#     choose:
#       conditions: "{{ 'Atmos' in state_attr('media_player.onkyo', 'format') }}"
#       sequence:
#         - service: light.turn_on
#           data:
#             entity_id: light.atmos_light