- alias: "Family room: lights"
  id: 8b53f10d-df56-421e-9e89-08cb39f16c7d
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_bright_inside

    - platform: time
      at:
        - input_datetime.time_goodmorning
        - input_datetime.time_goodnight

  action:
    choose:
      - conditions:
          - condition: state
            # when there is daylight
            entity_id:
              - input_boolean.house_mode_bright_inside
            state: "on"

        sequence:
          - &turn_off # turn off lights
            service: light.turn_off
            target:
              entity_id:
                - light.family_room_window_1
                - light.mushroom_lamp
            data:
              transition: 5

      - conditions:
          - condition: or
            conditions:
              - condition: and
                # turn on lights if
                conditions:
                  - condition: time
                    # at specific time in the morning
                    after: input_datetime.time_goodmorning
                    # but before a specific time in the evening
                    before: input_datetime.time_goodnight

        sequence:
          - &scene_turn_on
            service: scene.turn_on
            target:
              entity_id:
                - scene.family_room_ambience_lights_cozy
                - scene.family_room_window_lights_cozy
            data:
              transition: 5

    default:
      - *turn_off
