- alias: "Annie: error"
  id: b3c00dc3-b327-498e-9076-8ab6ed4fb3b7
  mode: queued
  trace:
    stored_traces: 10

  trigger:
    - platform: state
      entity_id:
        - sensor.am430x_status_id
      to:
        - "7"
      not_from:
        - "unknown"
        - "unavailable"
        - "0" # 0 = please wait

  action:
    - delay:
        seconds: 1

    - service: notify.castle
      data:
        title: " "
        message: " "
        data:
          photo:
            - url: "https://ha.regerar.se{{ state_attr('image.annie_map', 'entity_picture') }}"
              caption: "Annie: {{states('sensor.am430x_status')}} - {{states('sensor.am430x_substatus')}} ({{states('sensor.am430x_substatus_id')}})"
