- alias: "Annie: error"
  id: b3c00dc3-b327-498e-9076-8ab6ed4fb3b7
  mode: queued
  trace:
    stored_traces: 10

  trigger:
    - platform: state
      entity_id:
        - sensor.am430x_status_id
      to:
        - "7"
      not_from:
        - "unknown"
        - "unavailable"
        - "0" # 0 = please wait

  action:
    - delay:
        seconds: 1

    # - service: notify.castle
    #   data:
    #     title: " "
    #     message: " "
    #     data:
    #       photo:
    #         - url: "https://ha.regerar.se{{ state_attr('image.annie_map', 'entity_picture') }}"
    #           caption: "Annie: {{states('sensor.am430x_status')}} - {{ states('input_text.annie_last_substatus') if states('sensor.am430x_substatus') == '' else states('sensor.am430x_substatus') }}"

    - service: notify.castle_log
      data:
        title: "Annie: {{states('sensor.am430x_status')}}"
        message: "{{ states('input_text.annie_last_substatus') if states('sensor.am430x_substatus') == '' else states('sensor.am430x_substatus') }}"
        data:
          location:
            latitude: "{{state_attr('device_tracker.am430x_gps', 'latitude')}}"
            longitude: "{{state_attr('device_tracker.am430x_gps', 'longitude')}}"

- alias: "Annie: set last substatus"
  id: 0819562f-9de5-4c95-990f-f44f88e0e381
  mode: queued
  trace:
    stored_traces: 10

  trigger:
    - platform: state
      entity_id:
        - sensor.am430x_substatus
  action:
    service: input_text.set_value
    target:
      entity_id: input_text.annie_last_substatus
    data:
      value: "{{ trigger.from_state.state }}"

- alias: "Annie: park when wet"
  id: 00520d65-1bb5-425b-8743-ee58d488653e
  trace:
    stored_traces: 10
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.gw3000a_rain_state_piezo
      from: "off"
      to: "on"

  actions:
    - action: button.press
      data: {}
      target:
        entity_id: button.am430x_eod

- alias: "Annie: resume mowing when dry"
  id: f248b77a-854a-4099-9485-b816045b90fa
  trace:
    stored_traces: 10
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.gw3000a_rain_state_piezo
      from: "on"
      to: "off"
      for:
        minutes: 60

  actions:
    - action: button.press
      data: {}
      target:
        entity_id: button.am430x_auto
