- alias: "House: door bell"
  id: 54036205-5324-4d60-aa95-e24f9ff99a34
  trace:
    stored_traces: 25
  mode: single

  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.wardrobe_terrace_bt_proxy_door_bell
        - binary_sensor.front_door_doorbell_ding
      from: "off"
      to: "on"

  action:
    - service: camera.snapshot
      data:
        filename: /config/www/images/doorbell_last_image.jpg
      target:
        entity_id: camera.front
    - delay:
        seconds: 3
    - action: notify.family
      data:
        title: "Dörrklockan"
        message: "Det ringer på dörrklockan!"
        data:
          image: "/local/images/doorbell_last_image.jpg"
          tag: door_bell
          timeout: 900
