- alias: "Spot price change"
  id: 0fc03d6f-62ca-4a0f-b8a6-52873e84d2d5
  trace:
    stored_traces: 25
  mode: single

  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded

    - trigger: state
      entity_id:
        - sensor.nordpool_se2

  actions:
    - action: input_number.set_value
      target:
        entity_id: input_number.electricity_price_level
      data:
        value: >
          {% set s = states('sensor.nordpool_se2')|float %}

          {% if s > 2.5 %} {% set p = 5 %}
          {% elif s > 1.5 %} {% set p = 4 %}
          {% elif s > 0.5 %} {% set p = 3 %}
          {% elif s >= 0 %} {% set p = 2 %}
          {% elif s < 0 %} {% set p = 1 %}
          {% endif %}
          {% if states('sensor.momentary_active_export')|float > 1 and p <= 2 %}
            {% set p = p - 1 %}
          {% endif %}
          {{p}}
