- alias: "House: vvc"
  id: 9108277c-4a52-47f6-8481-32813b096a0f
  mode: queued
  trace:
    stored_traces: 25

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_away
        - input_boolean.house_mode_sleep
        - zone.home
        - input_number.electricity_price_level
        - input_boolean.house_vvc_preheat

    - platform: time
      at:
        - &time_start "06:00:00"
        - &time_stop "21:00:00"
        - &morning_start "06:30:00"
        - &morning_end "08:00:00"
        - &lunch_start "10:45:00"
        - &lunch_end "11:30:00"
        - &dinner_start "16:00:00"
        - &dinner_end "18:00:00"

  condition: []

  action:
    choose:
      - conditions:
          - alias: "when house mode is set to"
            condition: or
            conditions:
              - alias: "away"
                condition: state
                entity_id: input_boolean.house_mode_away
                state: "on"
              - alias: "sleeping"
                condition: state
                entity_id: input_boolean.house_mode_sleep
                state: "on"
        sequence:
          - &turn_off_vvc
            alias: "turn off vvc"
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.house_vvc

      - conditions:
          - alias: "when spot price is too high"
            condition: numeric_state
            entity_id: input_number.electricity_price_level
            above: 3
        sequence:
          - *turn_off_vvc

      - conditions:
          - alias: "when preheat is active"
            condition: state
            entity_id: input_boolean.house_vvc_preheat
            state: "on"
        sequence:
          - &turn_on_vvc
            alias: "turn on vvc"
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.house_vvc

      - conditions: "{{ (states('zone.home')|int(0) == 1 and state_attr('zone.home', 'persons')[0] == 'person.linus' and states('input_boolean.workday_linus') == 'on') }}"
        # if i'm the only one at home and working
        sequence:
          - choose:
              - conditions:
                  - condition: or
                    conditions:
                      - condition: time
                        after: *morning_start
                        before: *morning_end
                      - condition: time
                        after: *lunch_start
                        before: *lunch_end
                      - condition: time
                        after: *dinner_start
                        before: *dinner_end
                sequence:
                  - *turn_on_vvc
            default:
              - *turn_off_vvc

      - conditions:
          - condition: time
            # quickfix until a proper way to determine if we are sleeping or not is in place
            after: *time_start
            before: *time_stop
        sequence:
          - *turn_on_vvc

    default:
      - *turn_off_vvc

- alias: "House: vvc switch"
  id: b755328d-ad0c-4f7f-94e4-50d583e06639
  mode: queued
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_vvc
        - input_boolean.house_vvc_block
        - input_boolean.boilerroom_manual_mode
        - input_number.vvc_stop
        #- input_number.vvc_start
        - input_number.vvc_diff

    - platform: numeric_state
      id: vvc_start
      entity_id:
        - sensor.wardrobe_house_hot_water_supply
      #below: input_number.vvc_start
      below: 0
      value_template: >
        {% set offset = states('input_number.vvc_stop')|float(0) - states('input_number.vvc_diff')|float(0) %}
        {{ states('sensor.wardrobe_house_hot_water_supply')|float(0) - offset }}

    - platform: numeric_state
      id: vvc_stop
      entity_id:
        - sensor.wardrobe_house_hot_water_supply
      above: input_number.vvc_stop

  condition: []

  action:
    choose:
      - conditions:
          - alias: "if block switch is active"
            condition: state
            entity_id:
              - input_boolean.house_vvc_block
            state: "on"

        sequence:
          alias: "always turn off vvc"
          service: switch.turn_off
          target:
            entity_id: switch.vvc_pump

      - conditions:
          condition: and
          conditions:
            - alias: "if vvc should be on"
              condition: state
              entity_id:
                - input_boolean.house_vvc
              state: "on"
            - alias: "and manual mode is off"
              condition: state
              entity_id:
                - input_boolean.boilerroom_manual_mode
              state: "off"

        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id:
                      - sensor.wardrobe_house_hot_water_supply
                    below: input_number.vvc_stop
                sequence:
                  service: switch.turn_on
                  target:
                    entity_id: switch.vvc_pump
            default:
              - &turn_off_pump
                service: switch.turn_off
                target:
                  entity_id: switch.vvc_pump

    default:
      - *turn_off_pump

- alias: "House: vvc preheat"
  id: d7bb04cd-922f-4515-8eba-90c59f2e37c8
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_vvc_preheat
      from: "off"
      to: "on"
      for: &preheat "00:10:00"

  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.house_vvc_preheat
