- alias: "House: vvc"
  id: 9108277c-4a52-47f6-8481-32813b096a0f
  trace:
    stored_traces: 25

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      id: movement
      entity_id:
        - group.motion_bathrooms
        # - binary_sensor.bathroom_downstairs_presence
        # - binary_sensor.bathroom_upstairs_presence
      from: "off"
      to: "on"

    - platform: state
      entity_id:
        - group.motion_bathrooms
        # - binary_sensor.bathroom_downstairs_presence
        # - binary_sensor.bathroom_upstairs_presence
      from: "on"
      to: "off"
      for:
        seconds: 10

    - platform: state
      entity_id:
        - input_boolean.house_mode_away
        - input_boolean.house_mode_sleep

    - platform: time
      at: &lunch_start "10:50:00"
    - platform: time
      at: &lunch_end "11:30:00"
    - platform: time
      at: &dinner_start "16:50:00"
    - platform: time
      at: &dinner_end "18:00:00"

    - platform: state
      id: back_from_workout
      entity_id:
        - person.linus
      to: home

    - platform: state
      entity_id:
        - person.linus
      from: "not_home"
      to: "home"
      for:
        minutes: 5

    - platform: state
      entity_id:
        - input_boolean.house_vvc_preheat

  condition: []

  action:
    choose:
      - conditions:
          - alias: "when house mode is set to"
            condition: or
            conditions:
              - alias: "away"
                condition: state
                entity_id: input_boolean.house_mode_away
                state: "on"
              - alias: "sleeping"
                condition: state
                entity_id: input_boolean.house_mode_sleep
                state: "on"
        sequence:
          - &turn_off_vvc
            alias: "turn off vvc"
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.house_vvc

      - conditions:
          - alias: "when preheat is active"
            condition: state
            entity_id: input_boolean.house_vvc_preheat
            state: "on"
        sequence:
          - &turn_on_vvc
            alias: "turn on vvc"
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.house_vvc

      - conditions:
          - alias: "when entering a bathroom"
            condition: trigger
            id: movement
        sequence:
          - *turn_on_vvc

      - conditions:
          - alias: "if the time is"
            condition: or
            conditions:
              - alias: "during lunch"
                condition: time
                after: *lunch_start
                before: *lunch_end
              - alias: "during dinner"
                condition: time
                after: *dinner_start
                before: *dinner_end
        sequence:
          - *turn_on_vvc

      - conditions:
          - alias: "when getting back from workout"
            condition: and
            conditions:
              - alias: "if I just got back home"
                condition: trigger
                id: back_from_workout
              - alias: "and time is between"
                condition: time
                after: "19:15:00"
                before: "20:00:00"
                weekday:
                  - tue
                  - wed
                  - thu

        sequence:
          - *turn_on_vvc

    default:
      - *turn_off_vvc

- alias: "House: vvc switch"
  id: b755328d-ad0c-4f7f-94e4-50d583e06639
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_vvc
        - input_boolean.boilerroom_manual_mode

  condition: []

  action:
    choose:
      - conditions:
          condition: and
          conditions:
            - alias: "if vvc should be on"
              condition: state
              entity_id:
                - input_boolean.house_vvc
              state: "on"
            - alias: "and manual mode is off"
              condition: state
              entity_id:
                - input_boolean.boilerroom_manual_mode
              state: "off"

        sequence:
          service: switch.turn_on
          target:
            entity_id: switch.heatpump_vvc

    default:
      service: switch.turn_off
      target:
        entity_id: switch.heatpump_vvc


- alias: "House: vvc preheat"
  id: d7bb04cd-922f-4515-8eba-90c59f2e37c8
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_vvc_preheat
      from: "off"
      to: "on"
      for: &preheat "00:05:00"

  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.house_vvc_preheat