- alias: "House: indoor lights"
  id: 537b00d9-dc8b-4feb-817a-4cef28dc84f4
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_daylight

    - platform: time
      at: 
        - input_datetime.time_goodmorning
        - input_datetime.time_goodmorning_weekend
        - input_datetime.time_goodnight
      
  action:
      choose:
      - conditions:

        - condition: state
          # turn off if daylight
          entity_id:
            - input_boolean.house_mode_daylight
          state: "on"

        sequence:
          - &turn_off
            service: light.turn_off
            target:
              entity_id:
                - light.hallway_upstairs_wall
            data:
              transition: 5

      - conditions:
        - condition: or
          conditions:
          - condition: and
            # turn on lights
            conditions:
              # in the morning
              - condition: time
                after: input_datetime.time_goodmorning
                # at a workday
              - condition: state
                entity_id:
                  - input_boolean.house_mode_workday
                state: "on"

          - condition: and
            # turn on the lights
            conditions:
              - condition: time
                # at specific time in the morning
                after: input_datetime.time_goodmorning_weekend
              - condition: state
                # when it's not a workday
                entity_id:
                  - input_boolean.house_mode_workday
                state: "off"
          
          - condition: and
            # turn on lights
            conditions:
              - condition: state
                # at sunset
                entity_id:
                  - input_boolean.house_mode_daylight
                state: "off"
              - condition: time
                # if it's not too late
                before: input_datetime.time_goodnight

        sequence:
          - choose:
            - conditions:
              - condition: state
                entity_id:
                  - input_boolean.house_mode_sleep
                state: "on"
              sequence:
                - &turn_on
                  service: light.turn_on
                  target:
                    entity_id:
                      - light.hallway_upstairs_wall
                  data:
                    transition: 5
                    brightness: 1

            - conditions:
              - condition: state
                entity_id:
                  - input_boolean.house_mode_sleep
                state: "off"
              sequence:
                - <<: *turn_on
                  data:
                    brightness: 255
                
      default:
        - *turn_off
      