- alias: "House: indoor lights"
  id: 537b00d9-dc8b-4feb-817a-4cef28dc84f4
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_bright_inside

    - platform: time
      at: 
        - input_datetime.time_goodmorning
        - input_datetime.time_goodmorning_weekend
        - input_datetime.time_goodnight
      
  action:
      choose:
      - conditions:

        - condition: state
          # when there is daylight
          entity_id:
            - input_boolean.house_mode_bright_inside
          state: "on"

        sequence:
          - &light_turn_off
            # turn off lights
            service: light.turn_off
            target:
              entity_id:
                - light.hallway_upstairs_wall
            data:
              transition: 5

      - conditions:
        - condition: or
          conditions:
          - condition: and
            # turn on lights if 
            conditions:
              - condition: time
                # at specific time in the morning
                after: input_datetime.time_goodmorning
                # but before a specific time in the evening
                before: input_datetime.time_goodnight
              - condition: state
                # at a workday
                entity_id:
                  - input_boolean.house_mode_workday
                state: "on"

          - condition: and
            # turn on lights if
            conditions:
              - condition: time
                # at specific time in the morning
                after: input_datetime.time_goodmorning_weekend
                # but before a specific time in the evening
                before: input_datetime.time_goodnight
              - condition: state
                # when it's not a workday
                entity_id:
                  - input_boolean.house_mode_workday
                state: "off"
          
          # - condition: and
          #   # turn on lights if
          #   conditions:
          #     - condition: state
          #       # at sunset
          #       entity_id:
          #         - input_boolean.house_mode_daylight
          #       state: "off"
          #     - condition: time
          #       # if it's not too late
          #       before: input_datetime.time_goodnight

        sequence:
          - choose:
            - conditions:
              # turn on with low brighness if sleep mode is on
              - condition: state
                entity_id:
                  - input_boolean.house_mode_sleep
                state: "on"
              sequence:
                - &light_turn_on
                  service: light.turn_on
                  target:
                    entity_id:
                      - light.hallway_upstairs_wall
                  data:
                    transition: 5
                    brightness: 1

            - conditions:
              # turn on with full brightness otherwise
              - condition: state
                entity_id:
                  - input_boolean.house_mode_sleep
                state: "off"
              sequence:
                - <<: *light_turn_on
                  data:
                    brightness: 255
                
      default:
        - *light_turn_off
      