- alias: "House: sleep mode"
  id: 2c24e58c-fb5f-4b5d-bcf1-6598c26125a1
  mode: queued

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type: automation_reloaded

    - platform: time
      id: "time"
      at: input_datetime.house_reset_settings
    
    - platform: state
      id: "manual"
      entity_id:
        - input_boolean.bedroom_manual_mode
        - input_boolean.kitchen_manual_mode
        - input_boolean.livingroom_manual_mode
      from: "off"
      to: "on"

    - platform: state
      entity_id:
        - lock.front_door
      from: "locked"
      to: "unlocked"
      
  action:
    - choose:
      # reset to sleeping at night until I figure out a better way to detect it
      - conditions:
          condition: trigger
          id: "time"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.house_mode_sleep

      - conditions:
          condition: trigger
          id: "manual"
        sequence:
          - &turn_off
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.house_mode_sleep
          
      default:
        - *turn_off