- alias: "House: guest mode"
  id: b480b798-c2f5-4ec9-ab4e-da96fe5590f9
  mode: queued

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type: automation_reloaded
    
    - platform: state
      id: "tracker"
      entity_id:
        - group.guests
      
  action:
    - choose:
      - conditions:
          condition: state
          entity_id:
            - group.guests
          state: "home"
        
        sequence:
          - &turn_on
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.house_mode_guests
          
      default:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.house_mode_guests
