- alias: "House: bright inside mode"
  id: 44bed364-c081-4720-b8f5-60aaae177d4f
  mode: queued

  triggers:
    # - platform: homeassistant
    #   event: start

    - trigger: event
      event_type: automation_reloaded

    - trigger: state
      entity_id:
        - input_number.sun_elevation_limit

    - trigger: numeric_state
      id: "sun"
      entity_id:
        - sun.sun
      attribute: elevation
      above: &sun_elevation input_number.sun_elevation_limit

    - trigger: numeric_state
      id: lightlevel_day
      entity_id:
        - sensor.outdoor_illuminance_min
      above: input_number.lightlevel_limit_indoor
      for:
        minutes: 5

    - trigger: numeric_state
      id: lightlevel_night
      entity_id:
        - sensor.outdoor_illuminance_min
      below: input_number.lightlevel_limit_indoor
      for:
        minutes: 5

  condition: []

  action:
    choose:
      - conditions:
          - condition: numeric_state
            # if sun elevation is high enough
            entity_id:
              - sensor.sun_elevation
            above: input_number.sun_elevation_limit
          - condition: numeric_state
            # and its bright enough
            entity_id:
              - sensor.outdoor_illuminance_min
            above: input_number.lightlevel_limit_indoor

        sequence:
          - action: input_boolean.turn_on
            # turn on daylight mode
            target:
              entity_id: input_boolean.house_mode_bright_inside

    default:
      # turn off daylight mode, it's dark inside
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.house_mode_bright_inside
