- alias: "House: daylight mode"
  id: 076988f1-1e78-4cdd-96fd-83ff83431e1c
  mode: queued
  trace:
    stored_traces: 25

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type: automation_reloaded

    - platform: numeric_state
      id: "sun"
      entity_id:
        - sun.sun
      attribute: elevation
      above: &sun_elevation "-2.0"
    
    - platform: state
      id: lightlevel
      entity_id:
        - sensor.motion_driveway_lightlevel

  condition:
    - condition: template
      value_template: '{{ trigger.to_state.state != "unavailable" }}'

  action:
      choose:
        - alias: "if it's less than 1 hour since last change"
          conditions:
          - condition: template
            value_template: >
              {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.house_mode_daylight.last_changed)) < 3600 }}
          sequence: []
            # do nothing


        - alias: "decide if we want to change to daylight mode"
          conditions:
          - condition: or
            conditions:
            - condition: trigger
              # if triggered by sunrise
              id: "sun"

            - condition: and
              conditions:
              - condition: numeric_state
                # if the sun is up
                entity_id:
                  - sun.sun
                attribute: elevation
                above: *sun_elevation

              - condition: numeric_state
                # and it's bright enough outside
                entity_id:
                  - sensor.motion_driveway_lightlevel
                above: 200

          sequence:
            - service: input_boolean.turn_on
              # turn on daylight mode
              target:
                entity_id: input_boolean.house_mode_daylight

      default:
        # turn off daylight mode, it's dark outside
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.house_mode_daylight