- alias: "House: bright inside mode"
  id: 44bed364-c081-4720-b8f5-60aaae177d4f
  mode: queued

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type: automation_reloaded

    - platform: numeric_state
      id: "sun"
      entity_id:
        - sun.sun
      attribute: elevation
      above: &sun_elevation "-2.0"
    
    - platform: state
      id: lightlevel
      entity_id:
        - sensor.motion_driveway_illuminance_lux

  condition:
    - condition: template
      value_template: '{{ false if trigger is defined and trigger.to_state is defined and trigger.to_state.state is defined and (trigger.to_state.state == "unavailable") else true }}'

  action:
      choose:
        - conditions:
          - condition: or
            conditions:
            - condition: trigger
              # if triggered by sunrise
              id: "sun"

            - condition: and
              conditions:
              - condition: numeric_state
                # if the sun is up
                entity_id:
                  - sun.sun
                attribute: elevation
                above: *sun_elevation

              - condition: numeric_state
                # and it's bright enough outside
                entity_id:
                  - sensor.motion_driveway_illuminance_lux
                above: 500

          sequence:
            - service: input_boolean.turn_on
              # turn on daylight mode
              target:
                entity_id: input_boolean.house_mode_bright_inside

      default:
        # turn off daylight mode, it's dark outside
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.house_mode_bright_inside