- alias: "Manual mode: turn off at defined time"
  id: 624c2596-32a1-44f7-864b-f56728145498
  trigger:
    - platform: time
      id: reset
      at: 
        - input_datetime.house_reset_settings
        - input_datetime.house_reset_settings_day

  action:
    choose:
      - conditions:
          - condition: trigger
            id: reset
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id:
                #- input_boolean.bedroom_manual_mode
                - input_boolean.parking_manual_mode
                - input_boolean.kitchen_manual_mode
                - input_boolean.livingroom_manual_mode
                - input_boolean.hallway_downstairs_manual_mode


- alias: "Manual mode: turn off after active for X minutes"
  id: ee354ef8-d169-4b44-ac27-83a19e418111
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_downstairs_manual_mode
      to: "on"
      for:
        minutes: &timeout 60

  action:
    choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.hallway_downstairs_manual_mode
            state: "on"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.hallway_downstairs_manual_mode
