- alias: "House: sleep mode"
  id: 2c24e58c-fb5f-4b5d-bcf1-6598c26125a1
  mode: queued

  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type: automation_reloaded

    - platform: time
      id: "time"
      at: input_datetime.house_reset_settings
    
    - platform: state
      id: "manual"
      entity_id:
        - input_boolean.bedroom_manual_mode
        - input_boolean.kitchen_manual_mode
        - input_boolean.livingroom_manual_mode
      from: "off"
      to: "on"

    - platform: state
      entity_id:
        - lock.front_door
      from: "locked"
      to: "unlocked"
      
    - platform: state
      id: "phone"
      entity_id:
        - sensor.kb2003_charger_type
      from: "ac"
      to: "none"

  variables:
    anchors:
      - &turn_on
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.house_mode_sleep
      - &turn_off
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.house_mode_sleep

  action:
    - choose:
      # reset to sleeping at night until I figure out a better way to detect it
      - conditions:
          condition: trigger
          id: "time"
        sequence:
          - *turn_on

      - conditions: 
        - condition: and
          conditions:
            - condition: trigger
              id: "phone"
            - condition: time
              after: "05:00:00"
              before: "09:00:00"
        sequence:
          - *turn_off
          

      - conditions:
          condition: trigger
          id: "manual"
        sequence:
          - *turn_off
          
      default:
        - *turn_off