- alias: "House: outdoor lights"
  id: 628f6bc0-9b4a-461f-878f-92b8de65fa7d
  trace:
    stored_traces: 10
  mode: queued
  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - trigger: state
      entity_id:
        - input_boolean.house_mode_outside_work

    - trigger: state
      id: daylight
      entity_id:
        - input_boolean.house_mode_daylight

    - trigger: state
      id: movement_on
      entity_id: group.motion_parking
      from:
        - "off"
      to:
        - "on"

    - trigger: state
      id: movement_off
      entity_id: group.motion_parking
      from:
        - "on"
      to:
        - "off"
      for:
        minutes: 5

  actions:
    choose:
      # work mode / all lights should be turned on
      - conditions:
          - condition: state
            entity_id:
              - input_boolean.house_mode_outside_work
            state: "on"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.outdoor_work
            data:
              transition: 2

      # when it gets dark (daylight helper turns off)
      - conditions:
          - condition: trigger
            id: daylight
          - condition: state
            entity_id: input_boolean.house_mode_daylight
            state: "off"
        sequence:
          - action: scene.turn_on
            target:
              entity_id: scene.outdoor_lights_default
            data:
              transition: 5

      # if there is no daylight
      - conditions:
          - condition: state
            entity_id: input_boolean.house_mode_daylight
            state: "off"
        sequence:
          - choose:
              # turn on lights when movement is detected
              - conditions:
                  - condition: trigger
                    id: movement_on
                sequence:
                  - action: scene.turn_on
                    target:
                      entity_id: scene.outdoor_parking_movement
                    data:
                      transition: 2
            # if no movement, return to default
            default:
              - action: scene.turn_on
                target:
                  entity_id: scene.outdoor_parking_default
                data:
                  transition: 5

    default:
      - action: light.turn_off
        target:
          entity_id: light.utomhuslampor
        data:
          transition: 5
