- alias: "House: outdoor lights"
  id: 628f6bc0-9b4a-461f-878f-92b8de65fa7d
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_daylight

    - platform: state
      id: movement
      entity_id: binary_sensor.motion_driveway_presence
      from: "off"
      to: "on"

  action:
    choose:
    - conditions:
        - condition: trigger
          # if triggered by movement
          id: "movement"
        - condition: state
          # and turned on (by daylight off)
          entity_id:
            - light.parkering_och_uppfart
          state: "on"

      sequence:
        # illuminate for a while and return to previous mode
        - service: scene.turn_on
          target:
            entity_id: scene.outdoor_parking_movement
          data:
            transition: 2
        - delay:
            minutes: 3
        
        - choose:
          # if it's still dark outside, return to previous
          - conditions:
              condition: state
              entity_id:
                - input_boolean.house_mode_daylight
              state: "off"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.outdoor_parking_default
                data:
                  transition: 5

          # if it's daylight, turn off lights
          - conditions:
              condition: state
              entity_id:
                - input_boolean.house_mode_daylight
              state: "on"
            sequence:
            - service: light.turn_off
              target:
                entity_id: light.parkering_och_uppfart
              data:
                transition: 5

    - conditions:
        condition: state
        # if not daylight
        entity_id:
          - input_boolean.house_mode_daylight
        state: "off"
      sequence:
        - service: scene.turn_on
          target:
            entity_id: scene.outdoor_lights_default
          data:
            transition: 5
        # - delay:
        #     seconds: 10
        # - service: homeassistant.turn_on
        #   entity_id:
        #     - switch.adaptive_lighting_entre
        #     - switch.adaptive_lighting_parkering_och_uppfart
        #     - switch.adaptive_lighting_dekoration_ute


    default:
      # - service: homeassistant.turn_off
      #   entity_id:
      #     - switch.adaptive_lighting_entre
      #     - switch.adaptive_lighting_parkering_och_uppfart
      #     - switch.adaptive_lighting_dekoration_ute
      # - delay:
      #     seconds: 50
      - service: light.turn_off
        target:
          entity_id: light.utomhuslampor
        data:
          transition: 5

