- alias: "House: outdoor lights"
  id: 628f6bc0-9b4a-461f-878f-92b8de65fa7d
  mode: queued
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded
        - scene_reloaded

    - platform: state
      entity_id:
        - input_boolean.house_mode_outside_work

    - platform: state
      id: daylight
      entity_id:
        - input_boolean.house_mode_daylight

    - platform: state
      entity_id: input_boolean.driveway_movement
      from: 
        - "on"
        - "off"
      to: 
        - "on"
        - "off"

  action:
    choose:
      - alias: "activate outdoor work mode"
        conditions:
          - alias: "when outside work mode is on"
            condition: state
            entity_id:
              - input_boolean.house_mode_outside_work
            state: "on"

        sequence:
          - alias: "activate outside work scene"
            service: scene.turn_on
            target:
              entity_id: scene.outdoor_work
            data:
              transition: 2

      - alias: "activate outdoor lights"
        conditions:
          - alias: "when triggered"
            condition: trigger
            id: daylight
          - alias: "and it turned off"
            condition: state
            entity_id: input_boolean.house_mode_daylight
            state: "off"

        sequence:
          - alias: "turn on lights"
            service: scene.turn_on
            target:
              entity_id: scene.outdoor_lights_default
            data:
              transition: 5

      - conditions:
        - alias: "if daylight is off"
          condition: state
          entity_id:
            - input_boolean.house_mode_daylight
          state: "off"

        sequence:
          - choose:
            - conditions:
                - alias: "movement is on"
                  condition: state
                  entity_id:
                    - input_boolean.driveway_movement
                  state: "on"
              sequence:
                - alias: "turn on movement mode"
                  service: scene.turn_on
                  target:
                    entity_id: scene.outdoor_parking_movement
                  data:
                    transition: 2
            default:
              - alias: "turn on default mode"
                service: scene.turn_on
                target:
                  entity_id: scene.outdoor_parking_default
                data:
                  transition: 5

    default:
      - service: light.turn_off
        target:
          entity_id: light.utomhuslampor
        data:
          transition: 5

