- alias: "Vac-it Ralph (uppe)"
  id: c5ae7db7-0bf6-4cd9-99fc-797126b13efd
  trace:
    stored_traces: 10

  trigger:
    - platform: time
      id: start_upstairs
      at: input_datetime.time_vacuum_upstairs

    - platform: template
      id: start_upstairs_notif
      value_template: "{{ now().strftime('%H:%M:%S') == (state_attr('input_datetime.time_vacuum_upstairs', 'timestamp')|as_datetime - timedelta(minutes=15)).strftime('%H:%M:%S') }}"
      # until offset for time trigger is supported: https://github.com/home-assistant/core/pull/56838

  condition: []

  variables:
    anchors:
      - &notif_phone
        service: notify.family
        data:
          title: "Vac-it Ralph"
          message: "Dags för städning om 15min!"
          data:
            tag: vacuum_ralph
            timeout: 900

  action:
    choose:
      - alias: "if we got guests at home"
        conditions:
          - condition: state
            entity_id: input_boolean.house_mode_guests
            state: "on"
        sequence: [] # do nothing

      - alias: "decide if we want to do something"
        conditions:
          - condition: and
            conditions:
              - alias: "triggered by start time"
                condition: trigger
                id:
                  - "start_upstairs_notif"
                  - "start_upstairs"

              - alias: "and weekday is on schedule"
                condition: time
                weekday:
                  - mon
                  - wed
                  - fri

        sequence:
          - variables:
              trigger: "{{ trigger.id }}"

          - alias: "choose what to do"
            choose:
              - alias: "if heads up was triggered"
                conditions: "{{ trigger == 'start_upstairs_notif' }}"
                sequence:
                  - *notif_phone

              - alias: "if actual start time was triggered"
                conditions: "{{ trigger == 'start_upstairs' }}"
                sequence:
                  alias: "start to clean"
                  service: vacuum.start
                  target:
                    entity_id:
                      - vacuum.vac_it_ralph

    # default:
    #     action

