- alias: "Vac-it Ralph (uppe)"
  id: c5ae7db7-0bf6-4cd9-99fc-797126b13efd
  trace:
    stored_traces: 10

  triggers:
    - trigger: time
      id: start_upstairs
      at: input_datetime.time_vacuum_upstairs

    - trigger: template
      id: start_upstairs_notif
      value_template: "{{ now().strftime('%H:%M:%S') == (state_attr('input_datetime.time_vacuum_upstairs', 'timestamp')|as_datetime - timedelta(minutes=15)).strftime('%H:%M:%S') }}"
      # until offset for time trigger is supported: https://github.com/home-assistant/core/pull/56838

  condition: []

  variables:
    anchors:
      - &notif_phone
        action: notify.family
        data:
          title: "Vac-it Ralph"
          message: "Dags för städning om 15min!"
          data:
            tag: vacuum_ralph
            timeout: 900

  actions:
    choose:
      - alias: "if we got guests at home"
        conditions:
          - condition: state
            entity_id: input_boolean.house_mode_guests
            state: "on"
        sequence: [] # do nothing

      - alias: "decide if we want to do something"
        conditions:
          - condition: and
            conditions:
              - alias: "triggered by start time"
                condition: trigger
                id:
                  - "start_upstairs_notif"
                  - "start_upstairs"

              - alias: "and weekday is on schedule"
                condition: time
                weekday:
                  - mon
                  - wed
                  - fri

        sequence:
          - variables:
              trigger: "{{ trigger.id }}"

          - alias: "choose what to do"
            choose:
              - alias: "if heads up was triggered"
                conditions: "{{ trigger == 'start_upstairs_notif' }}"
                sequence:
                  - *notif_phone

              - alias: "if actual start time was triggered"
                conditions: "{{ trigger == 'start_upstairs' }}"
                sequence:
                  alias: "start to clean"
                  action: vacuum.start
                  target:
                    entity_id:
                      - vacuum.vac_it_ralph

    # default:
    #     action

- alias: "Vac-it Ralph - disable map when not running"
  id: e7961fc1-6cee-4ffe-936c-8c49fc49642b
  trace:
    stored_traces: 10
  mode: restart

  triggers:
    - trigger: homeassistant
      event: start

    - trigger: event
      event_type:
        - automation_reloaded

    - trigger: state
      entity_id: vacuum.vac_it_ralph

  condition: []

  actions:
    - action: >
        {% if states('vacuum.vac_it_ralph') in ["unavailable", "unknown", "docked"] %}
          camera.turn_off
        {% else %}
          camera.turn_on
        {% endif %}
      target:
        entity_id: camera.xiaomi_cloud_map_extractor

- alias: "Vac-it Ralph - notify on error"
  id: 69b93815-b673-4bff-8e86-68c9586c12f9
  trace:
    stored_traces: 10

  triggers:
    - trigger: state
      entity_id:
        - vacuum.vac_it_ralph
      not_from: unavailable
      to: error

  actions:
    - action: notify.family
      data:
        title: "Vac-it Ralph"
        message: "Error: {{state_attr('vacuum.vac_it_ralph', 'error')}}"
        data:
          tag: vacuum_ralph
