- alias: "Vacuum: start"
  id: c5ae7db7-0bf6-4cd9-99fc-797126b13efd
  trace:
    stored_traces: 10

  trigger:

    - platform: time
      id: start_downstairs
      at: input_datetime.time_vacuum_downstairs

  condition: []

  action:
      choose:
      - alias: "if we got guests at home"
        conditions:
          - condition: state
            entity_id: input_boolean.house_mode_guests
            state: "on"
        sequence: []
          # do nothing
            
      - alias: "decide if we want to start clean cycle"
        conditions:
          - condition: and
            conditions:
              - alias: "triggered by start time"
                condition: trigger
                id: start_downstairs

              - alias: "and weekday is on schedule"
                condition: time
                weekday:
                  - mon
                  - wed
                  - fri
        sequence:
          alias: "start to clean"
          service: vacuum.start
          target:
            entity_id:
              - vacuum.vac_it_ralph

      # default:
      #     action
