- alias: "House: water leak"
  id: 995c171e-c998-42b6-9599-d5395bcca1d8
  trigger:
    - platform: homeassistant
      event: start

    - platform: event
      event_type:
        - automation_reloaded

    - platform: state
      id: "sensor"
      entity_id:
        - binary_sensor.water_sink_water_leak
        - binary_sensor.water_wardrobe_water_leak
        - binary_sensor.water_bedroom_ac_water_leak
      from: "off"
      to: "on"

  variables:
    data: &notify_data 
      importance: high
      ttl: 0
      #persistent: true
      tag: water_leak
      sticky: true
      visibility: public

    msg: >
      {% if trigger is defined and has_value('trigger.entity_id') %}
        {% set e = trigger.entity_id %}
      {% else %}
        {% set e = (
          [
            'binary_sensor.water_sink_water_leak', 
            'binary_sensor.water_wardrobe_water_leak', 
            'binary_sensor.water_bedroom_ac_water_leak'
          ]
          | select('is_state', 'on')
          | list)
        %}
      {% endif %}
      {% set mapper =  {
        'binary_sensor.water_sink_water_leak' : ' under diskbänken',
        'binary_sensor.water_wardrobe_water_leak' : ' i garderoben nere',
        'binary_sensor.water_bedroom_ac_water_leak': ', tanken till AC i sovrummet är full'
      } %}
      Vatten upptäckt{{mapper[e[0]] if e else ' någonstans'}}!

  action:
    choose:
      conditions:
        condition: or
        conditions:
          - condition: trigger
            id: "sensor"

          - condition: state
            entity_id:
              - binary_sensor.water_sink_water_leak
              - binary_sensor.water_wardrobe_water_leak
              - binary_sensor.water_bedroom_ac_water_leak
            state: "on"
            match: any

      sequence:
        - service: notify.family
          data_template:
            title: "Vattenläcka!"
            message: "{{msg}}"
            data: *notify_data
        - service: notify.castle
          data:
            title: "Vattenläcka!"
            message: "{{msg}}"
