substitutions:
  name: "conservatory-bt-proxy"
  description: "Bluetooth proxy"
  encryption_key: !secret api_key
  ota_password: !secret ota_pass
  log_level: DEBUG

packages:
  <<: !include_dir_named common
  board: !include boards/esp32dev.yaml
  btproxy: !include components/bt_proxy.yaml

mqtt: !remove
