substitutions:
  name: kitchen-bt-proxy
  description: "Bluetooth proxy"
  encryption_key: !secret api_key
  ota_password: !secret ota_pass
  log_level: DEBUG

packages:
  <<: !include_dir_named common
  board: !include boards/m5stamp_c3_bt.yaml
  btproxy: !include components/bt_proxy.yaml

mqtt: !remove

ble_client:
  - mac_address: 01:02:03:04:19:44
    id: anova_ble

climate:
  - platform: anova
    name: "Anova Precision Cooker"
    ble_client_id: anova_ble
    unit_of_measurement: c
