substitutions:
  name: "uptimetest"
  description: "Test of uptime sensor"
  encryption_key: !secret api_key
  ota_password: !secret ota_pass
  log_level: DEBUG

packages:
  <<: !include_dir_named common
  board: !include boards/wemos_d1_mini.yaml

esphome:
  friendly_name: ${name}

logger:
  baud_rate: 115200

mqtt: !remove

# sensor:
#   - platform: template
#     id: sensor_uptime_static_test
#     name: "Uptime static test"
#     device_class: timestamp
#     entity_category: diagnostic
#     accuracy_decimals: 0
#     update_interval: 10s
#     lambda: |-
#       return 1721497243;