substitutions:
  name: vindriktning
  description: "IKEA Vindriktning"
  encryption_key: !secret api_key
  ota_password: !secret ota_pass
  log_level: DEBUG

packages:
  <<: !include_dir_named common
  board: !include boards/wemos_d1_mini.yaml

api: !remove

uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter Concentration"