- alias: "Shower: start floor heating when shower starts"
  id: 818c0f02-8d9c-4859-bfc2-ecf54897bace
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.shower_derivative
      above: 50

  action:
    choose:
      - conditions:
          condition: state
          entity_id:
            - switch.laundry_room_channel_2
          state: "off"

        sequence:
          - service: notify.castle_log
            data:
              title: "Duschen"
              message: "N책gon har duschat, startar golvv채rmen (derivat: {{trigger.to_state.state}})"
          - service: switch.turn_on
            target:
              entity_id: switch.laundry_room_channel_2

- alias: "Shower: turn off floor heating"
  id: decdc5d9-5bd0-41ab-bf91-7e77a38e49b3
  mode: queued
  trigger:
    # - platform: state
    #   entity_id:
    #     - switch.laundry_room_channel_2
    #   to: "on"
    #   for:
    #     minutes: &timeout 120

    - platform: numeric_state
      id: end
      entity_id:
        - sensor.shower_derivative
      below: 50
      for:
        minutes: &timeout 120

    - platform: state
      id: motion
      entity_id:
        - binary_sensor.motion_bathroom_upstairs_occupancy

    - platform: time_pattern
      id: time
      minutes: "/5"

  action:
    choose:
      - conditions:
          condition: or
          conditions:
            - condition: and
              conditions:
                - condition: trigger
                  id:
                    - motion
                    - time
                - condition: state
                  entity_id:
                    - switch.laundry_room_channel_2
                  state: "on"
                  for:
                    minutes: &timeout_force 240
            
            - condition: trigger
              id: end


        sequence:
          - service: notify.castle_log
            data:
              title: "Duschen"
              message: "St채ngde av golvv채rmen nu efter {{ relative_time(states.switch.laundry_room_channel_2.last_changed) }}"
          - service: switch.turn_off
            target:
              entity_id: switch.laundry_room_channel_2
