- alias: "Shower: start floor heating when shower starts"
  id: 818c0f02-8d9c-4859-bfc2-ecf54897bace
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.shower_derivative
      above: 50

  action:
    - choose:
        - conditions:
            condition: state
            entity_id:
              - switch.laundry_room_channel_2
            state: "off"

          sequence:
            - service: notify.castle_log
              data:
                title: "Duschen"
                message: "N책gon har duschat, startar golvv채rmen (derivat: {{trigger.to_state.state}})"
            - service: switch.turn_on
              target:
                entity_id: switch.laundry_room_channel_2
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.shower_last_detected
      data:
        timestamp: "{{ now().timestamp() }}"

- alias: "Shower: turn off floor heating"
  id: decdc5d9-5bd0-41ab-bf91-7e77a38e49b3
  mode: queued
  trace:
    stored_traces: 25
  trigger:
    - platform: template
      id: endtime
      value_template: "{{ now().timestamp() - states.input_datetime.shower_last_detected.attributes.timestamp > 7200 }}"

    - platform: numeric_state
      id: endder
      entity_id:
        - sensor.shower_derivative
      below: 50
      for:
        minutes: &timeout 120

    - platform: state
      id: motion
      entity_id:
        - binary_sensor.motion_bathroom_upstairs_occupancy

    - platform: time_pattern
      id: time
      #minutes: "/5"
      minutes: "5"

  action:
    choose:
      - conditions:
          condition: or
          conditions:
            - condition: and
              conditions:
                - condition: trigger
                  id:
                    - motion
                    - time
                - condition: state
                  entity_id:
                    - switch.laundry_room_channel_2
                  state: "on"
                  for:
                    minutes: &timeout_force 240

            - condition: and
              conditions:
                - condition: trigger
                  id:
                    - endtime
                    - endder
                - condition: state
                  entity_id:
                    - switch.laundry_room_channel_2
                  state: "on"

        sequence:
          - service: notify.castle_log
            data:
              title: "Duschen"
              message: "St채ngde av golvv채rmen nu efter {{ (now().timestamp() - states.switch.laundry_room_channel_2.last_changed.timestamp())|timestamp_custom('%-Ht%-Mm', false) }} (trigger: {{trigger.id}})"
          - service: switch.turn_off
            target:
              entity_id: switch.laundry_room_channel_2
