# configuration moved to ui
# sensor:
#   - platform: version
#     name: current_ha_version
#     source: local

rest_command:
  report_ha_version:
    url: !secret ha_report_url
    method: POST
    content_type: "application/x-www-form-urlencoded"
    payload: "u={{ user }}&v={{ states.sensor.current_ha_version.state }}"
    verify_ssl: true

automation:
  - alias: "Report version on startup"
    id: 1faad88f-0758-4ef9-820e-d31df12a46b2
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: rest_command.report_ha_version
        data:
          user: !secret ha_report_user
