- platform: xiaomi_cloud_map_extractor
  host: !secret roborock_s5max_host
  token: !secret roborock_s5max_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ['all']
  map_transformation:
    scale: 3
  attributes:
    - calibration_points